[package]
name = "bxes_kafka"
version = "0.1.0"
edition = "2021"

[dependencies]
bxes = { path = "../bxes" }
rdkafka = { version = "0.36.2", features = ["cmake-build"] }
uuid = { version = "1.10.0", features = ["v4"] }
log = "0.4.25"
colog = "1.3.0"