[package]
name = "bxes_kafka"
version = "0.1.0"
edition = "2021"

[dependencies]
bxes = { path = "../bxes" }
rdkafka = { version = "0.25.0", features = ["cmake-build"] }
uuid = { version = "1.10.0", features = ["v4"] }