// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: backend_service.proto

package grpcmodels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrpcPredefinedPipelinePartsToBackendsMap struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	PartsToBackends []*GrpcPipelinePartToBackends `protobuf:"bytes,1,rep,name=parts_to_backends,json=partsToBackends,proto3" json:"parts_to_backends,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GrpcPredefinedPipelinePartsToBackendsMap) Reset() {
	*x = GrpcPredefinedPipelinePartsToBackendsMap{}
	mi := &file_backend_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcPredefinedPipelinePartsToBackendsMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPredefinedPipelinePartsToBackendsMap) ProtoMessage() {}

func (x *GrpcPredefinedPipelinePartsToBackendsMap) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPredefinedPipelinePartsToBackendsMap.ProtoReflect.Descriptor instead.
func (*GrpcPredefinedPipelinePartsToBackendsMap) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{0}
}

func (x *GrpcPredefinedPipelinePartsToBackendsMap) GetPartsToBackends() []*GrpcPipelinePartToBackends {
	if x != nil {
		return x.PartsToBackends
	}
	return nil
}

type GrpcPipelinePartToBackends struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartName      string                 `protobuf:"bytes,1,opt,name=part_name,json=partName,proto3" json:"part_name,omitempty"`
	Backends      []string               `protobuf:"bytes,2,rep,name=backends,proto3" json:"backends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcPipelinePartToBackends) Reset() {
	*x = GrpcPipelinePartToBackends{}
	mi := &file_backend_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcPipelinePartToBackends) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPipelinePartToBackends) ProtoMessage() {}

func (x *GrpcPipelinePartToBackends) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPipelinePartToBackends.ProtoReflect.Descriptor instead.
func (*GrpcPipelinePartToBackends) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{1}
}

func (x *GrpcPipelinePartToBackends) GetPartName() string {
	if x != nil {
		return x.PartName
	}
	return ""
}

func (x *GrpcPipelinePartToBackends) GetBackends() []string {
	if x != nil {
		return x.Backends
	}
	return nil
}

type GrpcFicusBackendInfo struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Name          string                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PipelineParts []*GrpcPipelinePartDescriptor `protobuf:"bytes,2,rep,name=pipeline_parts,json=pipelineParts,proto3" json:"pipeline_parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcFicusBackendInfo) Reset() {
	*x = GrpcFicusBackendInfo{}
	mi := &file_backend_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcFicusBackendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcFicusBackendInfo) ProtoMessage() {}

func (x *GrpcFicusBackendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcFicusBackendInfo.ProtoReflect.Descriptor instead.
func (*GrpcFicusBackendInfo) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{2}
}

func (x *GrpcFicusBackendInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GrpcFicusBackendInfo) GetPipelineParts() []*GrpcPipelinePartDescriptor {
	if x != nil {
		return x.PipelineParts
	}
	return nil
}

type GrpcPipelinePartDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcPipelinePartDescriptor) Reset() {
	*x = GrpcPipelinePartDescriptor{}
	mi := &file_backend_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcPipelinePartDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPipelinePartDescriptor) ProtoMessage() {}

func (x *GrpcPipelinePartDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPipelinePartDescriptor.ProtoReflect.Descriptor instead.
func (*GrpcPipelinePartDescriptor) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{3}
}

func (x *GrpcPipelinePartDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GrpcPipelineExecutionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Pipeline       *GrpcPipeline          `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	InitialContext []*GrpcContextKeyValue `protobuf:"bytes,2,rep,name=initialContext,proto3" json:"initialContext,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GrpcPipelineExecutionRequest) Reset() {
	*x = GrpcPipelineExecutionRequest{}
	mi := &file_backend_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcPipelineExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPipelineExecutionRequest) ProtoMessage() {}

func (x *GrpcPipelineExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPipelineExecutionRequest.ProtoReflect.Descriptor instead.
func (*GrpcPipelineExecutionRequest) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{4}
}

func (x *GrpcPipelineExecutionRequest) GetPipeline() *GrpcPipeline {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

func (x *GrpcPipelineExecutionRequest) GetInitialContext() []*GrpcContextKeyValue {
	if x != nil {
		return x.InitialContext
	}
	return nil
}

type GrpcProxyPipelineExecutionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Pipeline         *GrpcPipeline          `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	ContextValuesIds []*GrpcGuid            `protobuf:"bytes,2,rep,name=contextValuesIds,proto3" json:"contextValuesIds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GrpcProxyPipelineExecutionRequest) Reset() {
	*x = GrpcProxyPipelineExecutionRequest{}
	mi := &file_backend_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcProxyPipelineExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcProxyPipelineExecutionRequest) ProtoMessage() {}

func (x *GrpcProxyPipelineExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcProxyPipelineExecutionRequest.ProtoReflect.Descriptor instead.
func (*GrpcProxyPipelineExecutionRequest) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{5}
}

func (x *GrpcProxyPipelineExecutionRequest) GetPipeline() *GrpcPipeline {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

func (x *GrpcProxyPipelineExecutionRequest) GetContextValuesIds() []*GrpcGuid {
	if x != nil {
		return x.ContextValuesIds
	}
	return nil
}

type GrpcPipelinePartExecutionResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*GrpcPipelinePartExecutionResult_FinalResult
	//	*GrpcPipelinePartExecutionResult_PipelinePartResult
	//	*GrpcPipelinePartExecutionResult_LogMessage
	Result        isGrpcPipelinePartExecutionResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcPipelinePartExecutionResult) Reset() {
	*x = GrpcPipelinePartExecutionResult{}
	mi := &file_backend_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcPipelinePartExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPipelinePartExecutionResult) ProtoMessage() {}

func (x *GrpcPipelinePartExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPipelinePartExecutionResult.ProtoReflect.Descriptor instead.
func (*GrpcPipelinePartExecutionResult) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{6}
}

func (x *GrpcPipelinePartExecutionResult) GetResult() isGrpcPipelinePartExecutionResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GrpcPipelinePartExecutionResult) GetFinalResult() *GrpcPipelineFinalResult {
	if x != nil {
		if x, ok := x.Result.(*GrpcPipelinePartExecutionResult_FinalResult); ok {
			return x.FinalResult
		}
	}
	return nil
}

func (x *GrpcPipelinePartExecutionResult) GetPipelinePartResult() *GrpcPipelinePartResult {
	if x != nil {
		if x, ok := x.Result.(*GrpcPipelinePartExecutionResult_PipelinePartResult); ok {
			return x.PipelinePartResult
		}
	}
	return nil
}

func (x *GrpcPipelinePartExecutionResult) GetLogMessage() *GrpcPipelinePartLogMessage {
	if x != nil {
		if x, ok := x.Result.(*GrpcPipelinePartExecutionResult_LogMessage); ok {
			return x.LogMessage
		}
	}
	return nil
}

type isGrpcPipelinePartExecutionResult_Result interface {
	isGrpcPipelinePartExecutionResult_Result()
}

type GrpcPipelinePartExecutionResult_FinalResult struct {
	FinalResult *GrpcPipelineFinalResult `protobuf:"bytes,1,opt,name=finalResult,proto3,oneof"`
}

type GrpcPipelinePartExecutionResult_PipelinePartResult struct {
	PipelinePartResult *GrpcPipelinePartResult `protobuf:"bytes,2,opt,name=pipelinePartResult,proto3,oneof"`
}

type GrpcPipelinePartExecutionResult_LogMessage struct {
	LogMessage *GrpcPipelinePartLogMessage `protobuf:"bytes,3,opt,name=logMessage,proto3,oneof"`
}

func (*GrpcPipelinePartExecutionResult_FinalResult) isGrpcPipelinePartExecutionResult_Result() {}

func (*GrpcPipelinePartExecutionResult_PipelinePartResult) isGrpcPipelinePartExecutionResult_Result() {
}

func (*GrpcPipelinePartExecutionResult_LogMessage) isGrpcPipelinePartExecutionResult_Result() {}

type GrpcPipelinePartLogMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcPipelinePartLogMessage) Reset() {
	*x = GrpcPipelinePartLogMessage{}
	mi := &file_backend_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcPipelinePartLogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPipelinePartLogMessage) ProtoMessage() {}

func (x *GrpcPipelinePartLogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPipelinePartLogMessage.ProtoReflect.Descriptor instead.
func (*GrpcPipelinePartLogMessage) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{7}
}

func (x *GrpcPipelinePartLogMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GrpcPipelinePartResult struct {
	state            protoimpl.MessageState         `protogen:"open.v1"`
	ContextValues    []*GrpcContextValueWithKeyName `protobuf:"bytes,1,rep,name=contextValues,proto3" json:"contextValues,omitempty"`
	PipelinePartId   *GrpcGuid                      `protobuf:"bytes,2,opt,name=pipeline_part_id,json=pipelinePartId,proto3" json:"pipeline_part_id,omitempty"`
	PipelinePartName string                         `protobuf:"bytes,3,opt,name=pipeline_part_name,json=pipelinePartName,proto3" json:"pipeline_part_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GrpcPipelinePartResult) Reset() {
	*x = GrpcPipelinePartResult{}
	mi := &file_backend_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcPipelinePartResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPipelinePartResult) ProtoMessage() {}

func (x *GrpcPipelinePartResult) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPipelinePartResult.ProtoReflect.Descriptor instead.
func (*GrpcPipelinePartResult) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{8}
}

func (x *GrpcPipelinePartResult) GetContextValues() []*GrpcContextValueWithKeyName {
	if x != nil {
		return x.ContextValues
	}
	return nil
}

func (x *GrpcPipelinePartResult) GetPipelinePartId() *GrpcGuid {
	if x != nil {
		return x.PipelinePartId
	}
	return nil
}

func (x *GrpcPipelinePartResult) GetPipelinePartName() string {
	if x != nil {
		return x.PipelinePartName
	}
	return ""
}

type GrpcPipelineFinalResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ExecutionResult:
	//
	//	*GrpcPipelineFinalResult_Success
	//	*GrpcPipelineFinalResult_Error
	ExecutionResult isGrpcPipelineFinalResult_ExecutionResult `protobuf_oneof:"executionResult"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GrpcPipelineFinalResult) Reset() {
	*x = GrpcPipelineFinalResult{}
	mi := &file_backend_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcPipelineFinalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPipelineFinalResult) ProtoMessage() {}

func (x *GrpcPipelineFinalResult) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPipelineFinalResult.ProtoReflect.Descriptor instead.
func (*GrpcPipelineFinalResult) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{9}
}

func (x *GrpcPipelineFinalResult) GetExecutionResult() isGrpcPipelineFinalResult_ExecutionResult {
	if x != nil {
		return x.ExecutionResult
	}
	return nil
}

func (x *GrpcPipelineFinalResult) GetSuccess() *GrpcGuid {
	if x != nil {
		if x, ok := x.ExecutionResult.(*GrpcPipelineFinalResult_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *GrpcPipelineFinalResult) GetError() string {
	if x != nil {
		if x, ok := x.ExecutionResult.(*GrpcPipelineFinalResult_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isGrpcPipelineFinalResult_ExecutionResult interface {
	isGrpcPipelineFinalResult_ExecutionResult()
}

type GrpcPipelineFinalResult_Success struct {
	Success *GrpcGuid `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type GrpcPipelineFinalResult_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GrpcPipelineFinalResult_Success) isGrpcPipelineFinalResult_ExecutionResult() {}

func (*GrpcPipelineFinalResult_Error) isGrpcPipelineFinalResult_ExecutionResult() {}

var File_backend_service_proto protoreflect.FileDescriptor

const file_backend_service_proto_rawDesc = "" +
	"\n" +
	"\x15backend_service.proto\x12\x05ficus\x1a\x1bpipelines_and_context.proto\x1a\n" +
	"util.proto\x1a\x1bgoogle/protobuf/empty.proto\"y\n" +
	"(GrpcPredefinedPipelinePartsToBackendsMap\x12M\n" +
	"\x11parts_to_backends\x18\x01 \x03(\v2!.ficus.GrpcPipelinePartToBackendsR\x0fpartsToBackends\"U\n" +
	"\x1aGrpcPipelinePartToBackends\x12\x1b\n" +
	"\tpart_name\x18\x01 \x01(\tR\bpartName\x12\x1a\n" +
	"\bbackends\x18\x02 \x03(\tR\bbackends\"t\n" +
	"\x14GrpcFicusBackendInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12H\n" +
	"\x0epipeline_parts\x18\x02 \x03(\v2!.ficus.GrpcPipelinePartDescriptorR\rpipelineParts\"0\n" +
	"\x1aGrpcPipelinePartDescriptor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x93\x01\n" +
	"\x1cGrpcPipelineExecutionRequest\x12/\n" +
	"\bpipeline\x18\x01 \x01(\v2\x13.ficus.GrpcPipelineR\bpipeline\x12B\n" +
	"\x0einitialContext\x18\x02 \x03(\v2\x1a.ficus.GrpcContextKeyValueR\x0einitialContext\"\x91\x01\n" +
	"!GrpcProxyPipelineExecutionRequest\x12/\n" +
	"\bpipeline\x18\x01 \x01(\v2\x13.ficus.GrpcPipelineR\bpipeline\x12;\n" +
	"\x10contextValuesIds\x18\x02 \x03(\v2\x0f.ficus.GrpcGuidR\x10contextValuesIds\"\x85\x02\n" +
	"\x1fGrpcPipelinePartExecutionResult\x12B\n" +
	"\vfinalResult\x18\x01 \x01(\v2\x1e.ficus.GrpcPipelineFinalResultH\x00R\vfinalResult\x12O\n" +
	"\x12pipelinePartResult\x18\x02 \x01(\v2\x1d.ficus.GrpcPipelinePartResultH\x00R\x12pipelinePartResult\x12C\n" +
	"\n" +
	"logMessage\x18\x03 \x01(\v2!.ficus.GrpcPipelinePartLogMessageH\x00R\n" +
	"logMessageB\b\n" +
	"\x06result\"6\n" +
	"\x1aGrpcPipelinePartLogMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xcb\x01\n" +
	"\x16GrpcPipelinePartResult\x12H\n" +
	"\rcontextValues\x18\x01 \x03(\v2\".ficus.GrpcContextValueWithKeyNameR\rcontextValues\x129\n" +
	"\x10pipeline_part_id\x18\x02 \x01(\v2\x0f.ficus.GrpcGuidR\x0epipelinePartId\x12,\n" +
	"\x12pipeline_part_name\x18\x03 \x01(\tR\x10pipelinePartName\"q\n" +
	"\x17GrpcPipelineFinalResult\x12+\n" +
	"\asuccess\x18\x01 \x01(\v2\x0f.ficus.GrpcGuidH\x00R\asuccess\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\x11\n" +
	"\x0fexecutionResult2\x86\x01\n" +
	"\x1aGrpcBackendBalancerService\x12h\n" +
	"\x1dSetPipelinePartsToBackendsMap\x12/.ficus.GrpcPredefinedPipelinePartsToBackendsMap\x1a\x16.google.protobuf.Empty2\x82\x02\n" +
	"\x12GrpcBackendService\x12e\n" +
	"\x0fExecutePipeline\x12(.ficus.GrpcProxyPipelineExecutionRequest\x1a&.ficus.GrpcPipelinePartExecutionResult0\x01\x12>\n" +
	"\x13DropExecutionResult\x12\x0f.ficus.GrpcGuid\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\x0eGetBackendInfo\x12\x16.google.protobuf.Empty\x1a\x1b.ficus.GrpcFicusBackendInfoB\x0fZ\r./;grpcmodelsb\x06proto3"

var (
	file_backend_service_proto_rawDescOnce sync.Once
	file_backend_service_proto_rawDescData []byte
)

func file_backend_service_proto_rawDescGZIP() []byte {
	file_backend_service_proto_rawDescOnce.Do(func() {
		file_backend_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_service_proto_rawDesc), len(file_backend_service_proto_rawDesc)))
	})
	return file_backend_service_proto_rawDescData
}

var file_backend_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_backend_service_proto_goTypes = []any{
	(*GrpcPredefinedPipelinePartsToBackendsMap)(nil), // 0: ficus.GrpcPredefinedPipelinePartsToBackendsMap
	(*GrpcPipelinePartToBackends)(nil),               // 1: ficus.GrpcPipelinePartToBackends
	(*GrpcFicusBackendInfo)(nil),                     // 2: ficus.GrpcFicusBackendInfo
	(*GrpcPipelinePartDescriptor)(nil),               // 3: ficus.GrpcPipelinePartDescriptor
	(*GrpcPipelineExecutionRequest)(nil),             // 4: ficus.GrpcPipelineExecutionRequest
	(*GrpcProxyPipelineExecutionRequest)(nil),        // 5: ficus.GrpcProxyPipelineExecutionRequest
	(*GrpcPipelinePartExecutionResult)(nil),          // 6: ficus.GrpcPipelinePartExecutionResult
	(*GrpcPipelinePartLogMessage)(nil),               // 7: ficus.GrpcPipelinePartLogMessage
	(*GrpcPipelinePartResult)(nil),                   // 8: ficus.GrpcPipelinePartResult
	(*GrpcPipelineFinalResult)(nil),                  // 9: ficus.GrpcPipelineFinalResult
	(*GrpcPipeline)(nil),                             // 10: ficus.GrpcPipeline
	(*GrpcContextKeyValue)(nil),                      // 11: ficus.GrpcContextKeyValue
	(*GrpcGuid)(nil),                                 // 12: ficus.GrpcGuid
	(*GrpcContextValueWithKeyName)(nil),              // 13: ficus.GrpcContextValueWithKeyName
	(*emptypb.Empty)(nil),                            // 14: google.protobuf.Empty
}
var file_backend_service_proto_depIdxs = []int32{
	1,  // 0: ficus.GrpcPredefinedPipelinePartsToBackendsMap.parts_to_backends:type_name -> ficus.GrpcPipelinePartToBackends
	3,  // 1: ficus.GrpcFicusBackendInfo.pipeline_parts:type_name -> ficus.GrpcPipelinePartDescriptor
	10, // 2: ficus.GrpcPipelineExecutionRequest.pipeline:type_name -> ficus.GrpcPipeline
	11, // 3: ficus.GrpcPipelineExecutionRequest.initialContext:type_name -> ficus.GrpcContextKeyValue
	10, // 4: ficus.GrpcProxyPipelineExecutionRequest.pipeline:type_name -> ficus.GrpcPipeline
	12, // 5: ficus.GrpcProxyPipelineExecutionRequest.contextValuesIds:type_name -> ficus.GrpcGuid
	9,  // 6: ficus.GrpcPipelinePartExecutionResult.finalResult:type_name -> ficus.GrpcPipelineFinalResult
	8,  // 7: ficus.GrpcPipelinePartExecutionResult.pipelinePartResult:type_name -> ficus.GrpcPipelinePartResult
	7,  // 8: ficus.GrpcPipelinePartExecutionResult.logMessage:type_name -> ficus.GrpcPipelinePartLogMessage
	13, // 9: ficus.GrpcPipelinePartResult.contextValues:type_name -> ficus.GrpcContextValueWithKeyName
	12, // 10: ficus.GrpcPipelinePartResult.pipeline_part_id:type_name -> ficus.GrpcGuid
	12, // 11: ficus.GrpcPipelineFinalResult.success:type_name -> ficus.GrpcGuid
	0,  // 12: ficus.GrpcBackendBalancerService.SetPipelinePartsToBackendsMap:input_type -> ficus.GrpcPredefinedPipelinePartsToBackendsMap
	5,  // 13: ficus.GrpcBackendService.ExecutePipeline:input_type -> ficus.GrpcProxyPipelineExecutionRequest
	12, // 14: ficus.GrpcBackendService.DropExecutionResult:input_type -> ficus.GrpcGuid
	14, // 15: ficus.GrpcBackendService.GetBackendInfo:input_type -> google.protobuf.Empty
	14, // 16: ficus.GrpcBackendBalancerService.SetPipelinePartsToBackendsMap:output_type -> google.protobuf.Empty
	6,  // 17: ficus.GrpcBackendService.ExecutePipeline:output_type -> ficus.GrpcPipelinePartExecutionResult
	14, // 18: ficus.GrpcBackendService.DropExecutionResult:output_type -> google.protobuf.Empty
	2,  // 19: ficus.GrpcBackendService.GetBackendInfo:output_type -> ficus.GrpcFicusBackendInfo
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_backend_service_proto_init() }
func file_backend_service_proto_init() {
	if File_backend_service_proto != nil {
		return
	}
	file_pipelines_and_context_proto_init()
	file_util_proto_init()
	file_backend_service_proto_msgTypes[6].OneofWrappers = []any{
		(*GrpcPipelinePartExecutionResult_FinalResult)(nil),
		(*GrpcPipelinePartExecutionResult_PipelinePartResult)(nil),
		(*GrpcPipelinePartExecutionResult_LogMessage)(nil),
	}
	file_backend_service_proto_msgTypes[9].OneofWrappers = []any{
		(*GrpcPipelineFinalResult_Success)(nil),
		(*GrpcPipelineFinalResult_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_service_proto_rawDesc), len(file_backend_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_backend_service_proto_goTypes,
		DependencyIndexes: file_backend_service_proto_depIdxs,
		MessageInfos:      file_backend_service_proto_msgTypes,
	}.Build()
	File_backend_service_proto = out.File
	file_backend_service_proto_goTypes = nil
	file_backend_service_proto_depIdxs = nil
}
