// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.28.3
// source: backend_service.proto

package grpcmodels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrpcPredefinedPipelinePartsToBackendsMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartsToBackends []*GrpcPipelinePartToBackends `protobuf:"bytes,1,rep,name=parts_to_backends,json=partsToBackends,proto3" json:"parts_to_backends,omitempty"`
}

func (x *GrpcPredefinedPipelinePartsToBackendsMap) Reset() {
	*x = GrpcPredefinedPipelinePartsToBackendsMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcPredefinedPipelinePartsToBackendsMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPredefinedPipelinePartsToBackendsMap) ProtoMessage() {}

func (x *GrpcPredefinedPipelinePartsToBackendsMap) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPredefinedPipelinePartsToBackendsMap.ProtoReflect.Descriptor instead.
func (*GrpcPredefinedPipelinePartsToBackendsMap) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{0}
}

func (x *GrpcPredefinedPipelinePartsToBackendsMap) GetPartsToBackends() []*GrpcPipelinePartToBackends {
	if x != nil {
		return x.PartsToBackends
	}
	return nil
}

type GrpcPipelinePartToBackends struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartName string   `protobuf:"bytes,1,opt,name=part_name,json=partName,proto3" json:"part_name,omitempty"`
	Backends []string `protobuf:"bytes,2,rep,name=backends,proto3" json:"backends,omitempty"`
}

func (x *GrpcPipelinePartToBackends) Reset() {
	*x = GrpcPipelinePartToBackends{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcPipelinePartToBackends) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPipelinePartToBackends) ProtoMessage() {}

func (x *GrpcPipelinePartToBackends) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPipelinePartToBackends.ProtoReflect.Descriptor instead.
func (*GrpcPipelinePartToBackends) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{1}
}

func (x *GrpcPipelinePartToBackends) GetPartName() string {
	if x != nil {
		return x.PartName
	}
	return ""
}

func (x *GrpcPipelinePartToBackends) GetBackends() []string {
	if x != nil {
		return x.Backends
	}
	return nil
}

type GrpcFicusBackendInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PipelineParts []*GrpcPipelinePartDescriptor `protobuf:"bytes,2,rep,name=pipeline_parts,json=pipelineParts,proto3" json:"pipeline_parts,omitempty"`
}

func (x *GrpcFicusBackendInfo) Reset() {
	*x = GrpcFicusBackendInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcFicusBackendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcFicusBackendInfo) ProtoMessage() {}

func (x *GrpcFicusBackendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcFicusBackendInfo.ProtoReflect.Descriptor instead.
func (*GrpcFicusBackendInfo) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{2}
}

func (x *GrpcFicusBackendInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GrpcFicusBackendInfo) GetPipelineParts() []*GrpcPipelinePartDescriptor {
	if x != nil {
		return x.PipelineParts
	}
	return nil
}

type GrpcPipelinePartDescriptor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GrpcPipelinePartDescriptor) Reset() {
	*x = GrpcPipelinePartDescriptor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcPipelinePartDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPipelinePartDescriptor) ProtoMessage() {}

func (x *GrpcPipelinePartDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPipelinePartDescriptor.ProtoReflect.Descriptor instead.
func (*GrpcPipelinePartDescriptor) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{3}
}

func (x *GrpcPipelinePartDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GrpcPipelineExecutionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pipeline       *GrpcPipeline          `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	InitialContext []*GrpcContextKeyValue `protobuf:"bytes,2,rep,name=initialContext,proto3" json:"initialContext,omitempty"`
}

func (x *GrpcPipelineExecutionRequest) Reset() {
	*x = GrpcPipelineExecutionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcPipelineExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPipelineExecutionRequest) ProtoMessage() {}

func (x *GrpcPipelineExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPipelineExecutionRequest.ProtoReflect.Descriptor instead.
func (*GrpcPipelineExecutionRequest) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{4}
}

func (x *GrpcPipelineExecutionRequest) GetPipeline() *GrpcPipeline {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

func (x *GrpcPipelineExecutionRequest) GetInitialContext() []*GrpcContextKeyValue {
	if x != nil {
		return x.InitialContext
	}
	return nil
}

type GrpcProxyPipelineExecutionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pipeline         *GrpcPipeline `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	ContextValuesIds []*GrpcGuid   `protobuf:"bytes,2,rep,name=contextValuesIds,proto3" json:"contextValuesIds,omitempty"`
}

func (x *GrpcProxyPipelineExecutionRequest) Reset() {
	*x = GrpcProxyPipelineExecutionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcProxyPipelineExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcProxyPipelineExecutionRequest) ProtoMessage() {}

func (x *GrpcProxyPipelineExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcProxyPipelineExecutionRequest.ProtoReflect.Descriptor instead.
func (*GrpcProxyPipelineExecutionRequest) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{5}
}

func (x *GrpcProxyPipelineExecutionRequest) GetPipeline() *GrpcPipeline {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

func (x *GrpcProxyPipelineExecutionRequest) GetContextValuesIds() []*GrpcGuid {
	if x != nil {
		return x.ContextValuesIds
	}
	return nil
}

type GrpcPipelinePartExecutionResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*GrpcPipelinePartExecutionResult_FinalResult
	//	*GrpcPipelinePartExecutionResult_PipelinePartResult
	//	*GrpcPipelinePartExecutionResult_LogMessage
	Result isGrpcPipelinePartExecutionResult_Result `protobuf_oneof:"result"`
}

func (x *GrpcPipelinePartExecutionResult) Reset() {
	*x = GrpcPipelinePartExecutionResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcPipelinePartExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPipelinePartExecutionResult) ProtoMessage() {}

func (x *GrpcPipelinePartExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPipelinePartExecutionResult.ProtoReflect.Descriptor instead.
func (*GrpcPipelinePartExecutionResult) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{6}
}

func (m *GrpcPipelinePartExecutionResult) GetResult() isGrpcPipelinePartExecutionResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *GrpcPipelinePartExecutionResult) GetFinalResult() *GrpcPipelineFinalResult {
	if x, ok := x.GetResult().(*GrpcPipelinePartExecutionResult_FinalResult); ok {
		return x.FinalResult
	}
	return nil
}

func (x *GrpcPipelinePartExecutionResult) GetPipelinePartResult() *GrpcPipelinePartResult {
	if x, ok := x.GetResult().(*GrpcPipelinePartExecutionResult_PipelinePartResult); ok {
		return x.PipelinePartResult
	}
	return nil
}

func (x *GrpcPipelinePartExecutionResult) GetLogMessage() *GrpcPipelinePartLogMessage {
	if x, ok := x.GetResult().(*GrpcPipelinePartExecutionResult_LogMessage); ok {
		return x.LogMessage
	}
	return nil
}

type isGrpcPipelinePartExecutionResult_Result interface {
	isGrpcPipelinePartExecutionResult_Result()
}

type GrpcPipelinePartExecutionResult_FinalResult struct {
	FinalResult *GrpcPipelineFinalResult `protobuf:"bytes,1,opt,name=finalResult,proto3,oneof"`
}

type GrpcPipelinePartExecutionResult_PipelinePartResult struct {
	PipelinePartResult *GrpcPipelinePartResult `protobuf:"bytes,2,opt,name=pipelinePartResult,proto3,oneof"`
}

type GrpcPipelinePartExecutionResult_LogMessage struct {
	LogMessage *GrpcPipelinePartLogMessage `protobuf:"bytes,3,opt,name=logMessage,proto3,oneof"`
}

func (*GrpcPipelinePartExecutionResult_FinalResult) isGrpcPipelinePartExecutionResult_Result() {}

func (*GrpcPipelinePartExecutionResult_PipelinePartResult) isGrpcPipelinePartExecutionResult_Result() {
}

func (*GrpcPipelinePartExecutionResult_LogMessage) isGrpcPipelinePartExecutionResult_Result() {}

type GrpcPipelinePartLogMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GrpcPipelinePartLogMessage) Reset() {
	*x = GrpcPipelinePartLogMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcPipelinePartLogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPipelinePartLogMessage) ProtoMessage() {}

func (x *GrpcPipelinePartLogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPipelinePartLogMessage.ProtoReflect.Descriptor instead.
func (*GrpcPipelinePartLogMessage) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{7}
}

func (x *GrpcPipelinePartLogMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GrpcPipelinePartResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContextValues    []*GrpcContextValueWithKeyName `protobuf:"bytes,1,rep,name=contextValues,proto3" json:"contextValues,omitempty"`
	PipelinePartId   *GrpcGuid                      `protobuf:"bytes,2,opt,name=pipeline_part_id,json=pipelinePartId,proto3" json:"pipeline_part_id,omitempty"`
	PipelinePartName string                         `protobuf:"bytes,3,opt,name=pipeline_part_name,json=pipelinePartName,proto3" json:"pipeline_part_name,omitempty"`
}

func (x *GrpcPipelinePartResult) Reset() {
	*x = GrpcPipelinePartResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcPipelinePartResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPipelinePartResult) ProtoMessage() {}

func (x *GrpcPipelinePartResult) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPipelinePartResult.ProtoReflect.Descriptor instead.
func (*GrpcPipelinePartResult) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{8}
}

func (x *GrpcPipelinePartResult) GetContextValues() []*GrpcContextValueWithKeyName {
	if x != nil {
		return x.ContextValues
	}
	return nil
}

func (x *GrpcPipelinePartResult) GetPipelinePartId() *GrpcGuid {
	if x != nil {
		return x.PipelinePartId
	}
	return nil
}

func (x *GrpcPipelinePartResult) GetPipelinePartName() string {
	if x != nil {
		return x.PipelinePartName
	}
	return ""
}

type GrpcPipelineFinalResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to ExecutionResult:
	//
	//	*GrpcPipelineFinalResult_Success
	//	*GrpcPipelineFinalResult_Error
	ExecutionResult isGrpcPipelineFinalResult_ExecutionResult `protobuf_oneof:"executionResult"`
}

func (x *GrpcPipelineFinalResult) Reset() {
	*x = GrpcPipelineFinalResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcPipelineFinalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPipelineFinalResult) ProtoMessage() {}

func (x *GrpcPipelineFinalResult) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPipelineFinalResult.ProtoReflect.Descriptor instead.
func (*GrpcPipelineFinalResult) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{9}
}

func (m *GrpcPipelineFinalResult) GetExecutionResult() isGrpcPipelineFinalResult_ExecutionResult {
	if m != nil {
		return m.ExecutionResult
	}
	return nil
}

func (x *GrpcPipelineFinalResult) GetSuccess() *GrpcGuid {
	if x, ok := x.GetExecutionResult().(*GrpcPipelineFinalResult_Success); ok {
		return x.Success
	}
	return nil
}

func (x *GrpcPipelineFinalResult) GetError() string {
	if x, ok := x.GetExecutionResult().(*GrpcPipelineFinalResult_Error); ok {
		return x.Error
	}
	return ""
}

type isGrpcPipelineFinalResult_ExecutionResult interface {
	isGrpcPipelineFinalResult_ExecutionResult()
}

type GrpcPipelineFinalResult_Success struct {
	Success *GrpcGuid `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type GrpcPipelineFinalResult_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GrpcPipelineFinalResult_Success) isGrpcPipelineFinalResult_ExecutionResult() {}

func (*GrpcPipelineFinalResult_Error) isGrpcPipelineFinalResult_ExecutionResult() {}

var File_backend_service_proto protoreflect.FileDescriptor

var file_backend_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x66, 0x69, 0x63, 0x75, 0x73, 0x1a, 0x1b,
	0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x5f, 0x61, 0x6e, 0x64, 0x5f, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x75, 0x74, 0x69,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x79, 0x0a, 0x28, 0x47, 0x72, 0x70, 0x63, 0x50, 0x72, 0x65, 0x64,
	0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x61,
	0x72, 0x74, 0x73, 0x54, 0x6f, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x73, 0x4d, 0x61, 0x70,
	0x12, 0x4d, 0x0a, 0x11, 0x70, 0x61, 0x72, 0x74, 0x73, 0x5f, 0x74, 0x6f, 0x5f, 0x62, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x66, 0x69,
	0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x50, 0x61, 0x72, 0x74, 0x54, 0x6f, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x73, 0x52, 0x0f,
	0x70, 0x61, 0x72, 0x74, 0x73, 0x54, 0x6f, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x73, 0x22,
	0x55, 0x0a, 0x1a, 0x47, 0x72, 0x70, 0x63, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x50,
	0x61, 0x72, 0x74, 0x54, 0x6f, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x73, 0x12, 0x1b, 0x0a,
	0x09, 0x70, 0x61, 0x72, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x73, 0x22, 0x74, 0x0a, 0x14, 0x47, 0x72, 0x70, 0x63, 0x46, 0x69,
	0x63, 0x75, 0x73, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x48, 0x0a, 0x0e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x70,
	0x61, 0x72, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x66, 0x69, 0x63,
	0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x50,
	0x61, 0x72, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x52, 0x0d, 0x70,
	0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x61, 0x72, 0x74, 0x73, 0x22, 0x30, 0x0a, 0x1a,
	0x47, 0x72, 0x70, 0x63, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x61, 0x72, 0x74,
	0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x93,
	0x01, 0x0a, 0x1c, 0x47, 0x72, 0x70, 0x63, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2f, 0x0a, 0x08, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x50, 0x69,
	0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x08, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x12, 0x42, 0x0a, 0x0e, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73,
	0x2e, 0x47, 0x72, 0x70, 0x63, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x4b, 0x65, 0x79, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x0e, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x22, 0x91, 0x01, 0x0a, 0x21, 0x47, 0x72, 0x70, 0x63, 0x50, 0x72, 0x6f,
	0x78, 0x79, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x08, 0x70, 0x69,
	0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x66,
	0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x52, 0x08, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x3b, 0x0a, 0x10, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x49, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72,
	0x70, 0x63, 0x47, 0x75, 0x69, 0x64, 0x52, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x49, 0x64, 0x73, 0x22, 0x85, 0x02, 0x0a, 0x1f, 0x47, 0x72, 0x70,
	0x63, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x61, 0x72, 0x74, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x42, 0x0a, 0x0b,
	0x66, 0x69, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x50, 0x69,
	0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x48, 0x00, 0x52, 0x0b, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x4f, 0x0a, 0x12, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x66,
	0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x12, 0x70,
	0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x43, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72,
	0x70, 0x63, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x61, 0x72, 0x74, 0x4c, 0x6f,
	0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x6c, 0x6f, 0x67, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x36, 0x0a, 0x1a, 0x47, 0x72, 0x70, 0x63, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x50, 0x61, 0x72, 0x74, 0x4c, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xcb, 0x01, 0x0a, 0x16, 0x47, 0x72, 0x70,
	0x63, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x48, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x66, 0x69, 0x63,
	0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x57, 0x69, 0x74, 0x68, 0x4b, 0x65, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x0d,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x39, 0x0a,
	0x10, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e,
	0x47, 0x72, 0x70, 0x63, 0x47, 0x75, 0x69, 0x64, 0x52, 0x0e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x50, 0x61, 0x72, 0x74, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x70, 0x69, 0x70, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x61,
	0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x71, 0x0a, 0x17, 0x47, 0x72, 0x70, 0x63, 0x50, 0x69,
	0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x2b, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x47,
	0x75, 0x69, 0x64, 0x48, 0x00, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x16,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x11, 0x0a, 0x0f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x86, 0x01, 0x0a, 0x1a, 0x47, 0x72,
	0x70, 0x63, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x68, 0x0a, 0x1d, 0x53, 0x65, 0x74, 0x50,
	0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x61, 0x72, 0x74, 0x73, 0x54, 0x6f, 0x42, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x73, 0x4d, 0x61, 0x70, 0x12, 0x2f, 0x2e, 0x66, 0x69, 0x63, 0x75,
	0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x50, 0x72, 0x65, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64,
	0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x61, 0x72, 0x74, 0x73, 0x54, 0x6f, 0x42,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x73, 0x4d, 0x61, 0x70, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x32, 0x82, 0x02, 0x0a, 0x12, 0x47, 0x72, 0x70, 0x63, 0x42, 0x61, 0x63, 0x6b, 0x65,
	0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x65, 0x0a, 0x0f, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x28, 0x2e, 0x66,
	0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x50, 0x69,
	0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47,
	0x72, 0x70, 0x63, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x61, 0x72, 0x74, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x30, 0x01,
	0x12, 0x3e, 0x0a, 0x13, 0x44, 0x72, 0x6f, 0x70, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0f, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e,
	0x47, 0x72, 0x70, 0x63, 0x47, 0x75, 0x69, 0x64, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x45, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1b, 0x2e, 0x66, 0x69, 0x63,
	0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x46, 0x69, 0x63, 0x75, 0x73, 0x42, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x3b, 0x67, 0x72,
	0x70, 0x63, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_backend_service_proto_rawDescOnce sync.Once
	file_backend_service_proto_rawDescData = file_backend_service_proto_rawDesc
)

func file_backend_service_proto_rawDescGZIP() []byte {
	file_backend_service_proto_rawDescOnce.Do(func() {
		file_backend_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_backend_service_proto_rawDescData)
	})
	return file_backend_service_proto_rawDescData
}

var file_backend_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_backend_service_proto_goTypes = []interface{}{
	(*GrpcPredefinedPipelinePartsToBackendsMap)(nil), // 0: ficus.GrpcPredefinedPipelinePartsToBackendsMap
	(*GrpcPipelinePartToBackends)(nil),               // 1: ficus.GrpcPipelinePartToBackends
	(*GrpcFicusBackendInfo)(nil),                     // 2: ficus.GrpcFicusBackendInfo
	(*GrpcPipelinePartDescriptor)(nil),               // 3: ficus.GrpcPipelinePartDescriptor
	(*GrpcPipelineExecutionRequest)(nil),             // 4: ficus.GrpcPipelineExecutionRequest
	(*GrpcProxyPipelineExecutionRequest)(nil),        // 5: ficus.GrpcProxyPipelineExecutionRequest
	(*GrpcPipelinePartExecutionResult)(nil),          // 6: ficus.GrpcPipelinePartExecutionResult
	(*GrpcPipelinePartLogMessage)(nil),               // 7: ficus.GrpcPipelinePartLogMessage
	(*GrpcPipelinePartResult)(nil),                   // 8: ficus.GrpcPipelinePartResult
	(*GrpcPipelineFinalResult)(nil),                  // 9: ficus.GrpcPipelineFinalResult
	(*GrpcPipeline)(nil),                             // 10: ficus.GrpcPipeline
	(*GrpcContextKeyValue)(nil),                      // 11: ficus.GrpcContextKeyValue
	(*GrpcGuid)(nil),                                 // 12: ficus.GrpcGuid
	(*GrpcContextValueWithKeyName)(nil),              // 13: ficus.GrpcContextValueWithKeyName
	(*emptypb.Empty)(nil),                            // 14: google.protobuf.Empty
}
var file_backend_service_proto_depIdxs = []int32{
	1,  // 0: ficus.GrpcPredefinedPipelinePartsToBackendsMap.parts_to_backends:type_name -> ficus.GrpcPipelinePartToBackends
	3,  // 1: ficus.GrpcFicusBackendInfo.pipeline_parts:type_name -> ficus.GrpcPipelinePartDescriptor
	10, // 2: ficus.GrpcPipelineExecutionRequest.pipeline:type_name -> ficus.GrpcPipeline
	11, // 3: ficus.GrpcPipelineExecutionRequest.initialContext:type_name -> ficus.GrpcContextKeyValue
	10, // 4: ficus.GrpcProxyPipelineExecutionRequest.pipeline:type_name -> ficus.GrpcPipeline
	12, // 5: ficus.GrpcProxyPipelineExecutionRequest.contextValuesIds:type_name -> ficus.GrpcGuid
	9,  // 6: ficus.GrpcPipelinePartExecutionResult.finalResult:type_name -> ficus.GrpcPipelineFinalResult
	8,  // 7: ficus.GrpcPipelinePartExecutionResult.pipelinePartResult:type_name -> ficus.GrpcPipelinePartResult
	7,  // 8: ficus.GrpcPipelinePartExecutionResult.logMessage:type_name -> ficus.GrpcPipelinePartLogMessage
	13, // 9: ficus.GrpcPipelinePartResult.contextValues:type_name -> ficus.GrpcContextValueWithKeyName
	12, // 10: ficus.GrpcPipelinePartResult.pipeline_part_id:type_name -> ficus.GrpcGuid
	12, // 11: ficus.GrpcPipelineFinalResult.success:type_name -> ficus.GrpcGuid
	0,  // 12: ficus.GrpcBackendBalancerService.SetPipelinePartsToBackendsMap:input_type -> ficus.GrpcPredefinedPipelinePartsToBackendsMap
	5,  // 13: ficus.GrpcBackendService.ExecutePipeline:input_type -> ficus.GrpcProxyPipelineExecutionRequest
	12, // 14: ficus.GrpcBackendService.DropExecutionResult:input_type -> ficus.GrpcGuid
	14, // 15: ficus.GrpcBackendService.GetBackendInfo:input_type -> google.protobuf.Empty
	14, // 16: ficus.GrpcBackendBalancerService.SetPipelinePartsToBackendsMap:output_type -> google.protobuf.Empty
	6,  // 17: ficus.GrpcBackendService.ExecutePipeline:output_type -> ficus.GrpcPipelinePartExecutionResult
	14, // 18: ficus.GrpcBackendService.DropExecutionResult:output_type -> google.protobuf.Empty
	2,  // 19: ficus.GrpcBackendService.GetBackendInfo:output_type -> ficus.GrpcFicusBackendInfo
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_backend_service_proto_init() }
func file_backend_service_proto_init() {
	if File_backend_service_proto != nil {
		return
	}
	file_pipelines_and_context_proto_init()
	file_util_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_backend_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcPredefinedPipelinePartsToBackendsMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcPipelinePartToBackends); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcFicusBackendInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcPipelinePartDescriptor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcPipelineExecutionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcProxyPipelineExecutionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcPipelinePartExecutionResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcPipelinePartLogMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcPipelinePartResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcPipelineFinalResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_backend_service_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*GrpcPipelinePartExecutionResult_FinalResult)(nil),
		(*GrpcPipelinePartExecutionResult_PipelinePartResult)(nil),
		(*GrpcPipelinePartExecutionResult_LogMessage)(nil),
	}
	file_backend_service_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*GrpcPipelineFinalResult_Success)(nil),
		(*GrpcPipelineFinalResult_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_backend_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_backend_service_proto_goTypes,
		DependencyIndexes: file_backend_service_proto_depIdxs,
		MessageInfos:      file_backend_service_proto_msgTypes,
	}.Build()
	File_backend_service_proto = out.File
	file_backend_service_proto_rawDesc = nil
	file_backend_service_proto_goTypes = nil
	file_backend_service_proto_depIdxs = nil
}
