// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: context_values_service.proto

package grpcmodels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrpcContextValuePart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Bytes         []byte                 `protobuf:"bytes,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcContextValuePart) Reset() {
	*x = GrpcContextValuePart{}
	mi := &file_context_values_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcContextValuePart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcContextValuePart) ProtoMessage() {}

func (x *GrpcContextValuePart) ProtoReflect() protoreflect.Message {
	mi := &file_context_values_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcContextValuePart.ProtoReflect.Descriptor instead.
func (*GrpcContextValuePart) Descriptor() ([]byte, []int) {
	return file_context_values_service_proto_rawDescGZIP(), []int{0}
}

func (x *GrpcContextValuePart) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GrpcContextValuePart) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type GrpcDropContextValuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []*GrpcGuid            `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcDropContextValuesRequest) Reset() {
	*x = GrpcDropContextValuesRequest{}
	mi := &file_context_values_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcDropContextValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcDropContextValuesRequest) ProtoMessage() {}

func (x *GrpcDropContextValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_context_values_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcDropContextValuesRequest.ProtoReflect.Descriptor instead.
func (*GrpcDropContextValuesRequest) Descriptor() ([]byte, []int) {
	return file_context_values_service_proto_rawDescGZIP(), []int{1}
}

func (x *GrpcDropContextValuesRequest) GetIds() []*GrpcGuid {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_context_values_service_proto protoreflect.FileDescriptor

const file_context_values_service_proto_rawDesc = "" +
	"\n" +
	"\x1ccontext_values_service.proto\x12\x05ficus\x1a\x1bpipelines_and_context.proto\x1a\n" +
	"util.proto\x1a\x1bgoogle/protobuf/empty.proto\">\n" +
	"\x14GrpcContextValuePart\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\fR\x05bytes\"A\n" +
	"\x1cGrpcDropContextValuesRequest\x12!\n" +
	"\x03ids\x18\x01 \x03(\v2\x0f.ficus.GrpcGuidR\x03ids2\xf2\x01\n" +
	"\x18GrpcContextValuesService\x12A\n" +
	"\x0fSetContextValue\x12\x1b.ficus.GrpcContextValuePart\x1a\x0f.ficus.GrpcGuid(\x01\x12A\n" +
	"\x0fGetContextValue\x12\x0f.ficus.GrpcGuid\x1a\x1b.ficus.GrpcContextValuePart0\x01\x12P\n" +
	"\x11DropContextValues\x12#.ficus.GrpcDropContextValuesRequest\x1a\x16.google.protobuf.EmptyB\x0fZ\r./;grpcmodelsb\x06proto3"

var (
	file_context_values_service_proto_rawDescOnce sync.Once
	file_context_values_service_proto_rawDescData []byte
)

func file_context_values_service_proto_rawDescGZIP() []byte {
	file_context_values_service_proto_rawDescOnce.Do(func() {
		file_context_values_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_context_values_service_proto_rawDesc), len(file_context_values_service_proto_rawDesc)))
	})
	return file_context_values_service_proto_rawDescData
}

var file_context_values_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_context_values_service_proto_goTypes = []any{
	(*GrpcContextValuePart)(nil),         // 0: ficus.GrpcContextValuePart
	(*GrpcDropContextValuesRequest)(nil), // 1: ficus.GrpcDropContextValuesRequest
	(*GrpcGuid)(nil),                     // 2: ficus.GrpcGuid
	(*emptypb.Empty)(nil),                // 3: google.protobuf.Empty
}
var file_context_values_service_proto_depIdxs = []int32{
	2, // 0: ficus.GrpcDropContextValuesRequest.ids:type_name -> ficus.GrpcGuid
	0, // 1: ficus.GrpcContextValuesService.SetContextValue:input_type -> ficus.GrpcContextValuePart
	2, // 2: ficus.GrpcContextValuesService.GetContextValue:input_type -> ficus.GrpcGuid
	1, // 3: ficus.GrpcContextValuesService.DropContextValues:input_type -> ficus.GrpcDropContextValuesRequest
	2, // 4: ficus.GrpcContextValuesService.SetContextValue:output_type -> ficus.GrpcGuid
	0, // 5: ficus.GrpcContextValuesService.GetContextValue:output_type -> ficus.GrpcContextValuePart
	3, // 6: ficus.GrpcContextValuesService.DropContextValues:output_type -> google.protobuf.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_context_values_service_proto_init() }
func file_context_values_service_proto_init() {
	if File_context_values_service_proto != nil {
		return
	}
	file_pipelines_and_context_proto_init()
	file_util_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_context_values_service_proto_rawDesc), len(file_context_values_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_context_values_service_proto_goTypes,
		DependencyIndexes: file_context_values_service_proto_depIdxs,
		MessageInfos:      file_context_values_service_proto_msgTypes,
	}.Build()
	File_context_values_service_proto = out.File
	file_context_values_service_proto_goTypes = nil
	file_context_values_service_proto_depIdxs = nil
}
