// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: pm_models.proto

package grpcmodels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrpcSimpleEventLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Traces        []*GrpcSimpleTrace     `protobuf:"bytes,1,rep,name=traces,proto3" json:"traces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcSimpleEventLog) Reset() {
	*x = GrpcSimpleEventLog{}
	mi := &file_pm_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcSimpleEventLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcSimpleEventLog) ProtoMessage() {}

func (x *GrpcSimpleEventLog) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcSimpleEventLog.ProtoReflect.Descriptor instead.
func (*GrpcSimpleEventLog) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{0}
}

func (x *GrpcSimpleEventLog) GetTraces() []*GrpcSimpleTrace {
	if x != nil {
		return x.Traces
	}
	return nil
}

type GrpcSimpleTrace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*GrpcEvent           `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcSimpleTrace) Reset() {
	*x = GrpcSimpleTrace{}
	mi := &file_pm_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcSimpleTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcSimpleTrace) ProtoMessage() {}

func (x *GrpcSimpleTrace) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcSimpleTrace.ProtoReflect.Descriptor instead.
func (*GrpcSimpleTrace) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{1}
}

func (x *GrpcSimpleTrace) GetEvents() []*GrpcEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type GrpcEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Stamp         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=stamp,proto3" json:"stamp,omitempty"`
	Attributes    []*GrpcEventAttribute  `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcEvent) Reset() {
	*x = GrpcEvent{}
	mi := &file_pm_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcEvent) ProtoMessage() {}

func (x *GrpcEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcEvent.ProtoReflect.Descriptor instead.
func (*GrpcEvent) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{2}
}

func (x *GrpcEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GrpcEvent) GetStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Stamp
	}
	return nil
}

func (x *GrpcEvent) GetAttributes() []*GrpcEventAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type GrpcEventAttribute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*GrpcEventAttribute_Int
	//	*GrpcEventAttribute_String_
	//	*GrpcEventAttribute_Bool
	//	*GrpcEventAttribute_Double
	//	*GrpcEventAttribute_Guid
	//	*GrpcEventAttribute_Null
	//	*GrpcEventAttribute_Stamp
	//	*GrpcEventAttribute_Uint
	Value         isGrpcEventAttribute_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcEventAttribute) Reset() {
	*x = GrpcEventAttribute{}
	mi := &file_pm_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcEventAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcEventAttribute) ProtoMessage() {}

func (x *GrpcEventAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcEventAttribute.ProtoReflect.Descriptor instead.
func (*GrpcEventAttribute) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{3}
}

func (x *GrpcEventAttribute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GrpcEventAttribute) GetValue() isGrpcEventAttribute_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GrpcEventAttribute) GetInt() int64 {
	if x != nil {
		if x, ok := x.Value.(*GrpcEventAttribute_Int); ok {
			return x.Int
		}
	}
	return 0
}

func (x *GrpcEventAttribute) GetString_() string {
	if x != nil {
		if x, ok := x.Value.(*GrpcEventAttribute_String_); ok {
			return x.String_
		}
	}
	return ""
}

func (x *GrpcEventAttribute) GetBool() bool {
	if x != nil {
		if x, ok := x.Value.(*GrpcEventAttribute_Bool); ok {
			return x.Bool
		}
	}
	return false
}

func (x *GrpcEventAttribute) GetDouble() float64 {
	if x != nil {
		if x, ok := x.Value.(*GrpcEventAttribute_Double); ok {
			return x.Double
		}
	}
	return 0
}

func (x *GrpcEventAttribute) GetGuid() *GrpcGuid {
	if x != nil {
		if x, ok := x.Value.(*GrpcEventAttribute_Guid); ok {
			return x.Guid
		}
	}
	return nil
}

func (x *GrpcEventAttribute) GetNull() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Value.(*GrpcEventAttribute_Null); ok {
			return x.Null
		}
	}
	return nil
}

func (x *GrpcEventAttribute) GetStamp() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Value.(*GrpcEventAttribute_Stamp); ok {
			return x.Stamp
		}
	}
	return nil
}

func (x *GrpcEventAttribute) GetUint() uint64 {
	if x != nil {
		if x, ok := x.Value.(*GrpcEventAttribute_Uint); ok {
			return x.Uint
		}
	}
	return 0
}

type isGrpcEventAttribute_Value interface {
	isGrpcEventAttribute_Value()
}

type GrpcEventAttribute_Int struct {
	Int int64 `protobuf:"varint,2,opt,name=int,proto3,oneof"`
}

type GrpcEventAttribute_String_ struct {
	String_ string `protobuf:"bytes,3,opt,name=string,proto3,oneof"`
}

type GrpcEventAttribute_Bool struct {
	Bool bool `protobuf:"varint,4,opt,name=bool,proto3,oneof"`
}

type GrpcEventAttribute_Double struct {
	Double float64 `protobuf:"fixed64,5,opt,name=double,proto3,oneof"`
}

type GrpcEventAttribute_Guid struct {
	Guid *GrpcGuid `protobuf:"bytes,6,opt,name=guid,proto3,oneof"`
}

type GrpcEventAttribute_Null struct {
	Null *emptypb.Empty `protobuf:"bytes,7,opt,name=null,proto3,oneof"`
}

type GrpcEventAttribute_Stamp struct {
	Stamp *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=stamp,proto3,oneof"`
}

type GrpcEventAttribute_Uint struct {
	Uint uint64 `protobuf:"varint,9,opt,name=uint,proto3,oneof"`
}

func (*GrpcEventAttribute_Int) isGrpcEventAttribute_Value() {}

func (*GrpcEventAttribute_String_) isGrpcEventAttribute_Value() {}

func (*GrpcEventAttribute_Bool) isGrpcEventAttribute_Value() {}

func (*GrpcEventAttribute_Double) isGrpcEventAttribute_Value() {}

func (*GrpcEventAttribute_Guid) isGrpcEventAttribute_Value() {}

func (*GrpcEventAttribute_Null) isGrpcEventAttribute_Value() {}

func (*GrpcEventAttribute_Stamp) isGrpcEventAttribute_Value() {}

func (*GrpcEventAttribute_Uint) isGrpcEventAttribute_Value() {}

type GrpcHashesEventLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Traces        []*GrpcHashesLogTrace  `protobuf:"bytes,2,rep,name=traces,proto3" json:"traces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcHashesEventLog) Reset() {
	*x = GrpcHashesEventLog{}
	mi := &file_pm_models_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcHashesEventLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcHashesEventLog) ProtoMessage() {}

func (x *GrpcHashesEventLog) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcHashesEventLog.ProtoReflect.Descriptor instead.
func (*GrpcHashesEventLog) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{4}
}

func (x *GrpcHashesEventLog) GetTraces() []*GrpcHashesLogTrace {
	if x != nil {
		return x.Traces
	}
	return nil
}

type GrpcHashesLogTrace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []uint64               `protobuf:"varint,1,rep,packed,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcHashesLogTrace) Reset() {
	*x = GrpcHashesLogTrace{}
	mi := &file_pm_models_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcHashesLogTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcHashesLogTrace) ProtoMessage() {}

func (x *GrpcHashesLogTrace) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcHashesLogTrace.ProtoReflect.Descriptor instead.
func (*GrpcHashesLogTrace) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{5}
}

func (x *GrpcHashesLogTrace) GetEvents() []uint64 {
	if x != nil {
		return x.Events
	}
	return nil
}

type GrpcNamesEventLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Traces        []*GrpcNamesTrace      `protobuf:"bytes,1,rep,name=traces,proto3" json:"traces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcNamesEventLog) Reset() {
	*x = GrpcNamesEventLog{}
	mi := &file_pm_models_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcNamesEventLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcNamesEventLog) ProtoMessage() {}

func (x *GrpcNamesEventLog) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcNamesEventLog.ProtoReflect.Descriptor instead.
func (*GrpcNamesEventLog) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{6}
}

func (x *GrpcNamesEventLog) GetTraces() []*GrpcNamesTrace {
	if x != nil {
		return x.Traces
	}
	return nil
}

type GrpcNamesTrace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []string               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcNamesTrace) Reset() {
	*x = GrpcNamesTrace{}
	mi := &file_pm_models_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcNamesTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcNamesTrace) ProtoMessage() {}

func (x *GrpcNamesTrace) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcNamesTrace.ProtoReflect.Descriptor instead.
func (*GrpcNamesTrace) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{7}
}

func (x *GrpcNamesTrace) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

type GrpcPetriNet struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	Places         []*GrpcPetriNetPlace      `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
	Transitions    []*GrpcPetriNetTransition `protobuf:"bytes,2,rep,name=transitions,proto3" json:"transitions,omitempty"`
	InitialMarking *GrpcPetriNetMarking      `protobuf:"bytes,3,opt,name=initial_marking,json=initialMarking,proto3" json:"initial_marking,omitempty"`
	FinalMarking   *GrpcPetriNetMarking      `protobuf:"bytes,4,opt,name=final_marking,json=finalMarking,proto3" json:"final_marking,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GrpcPetriNet) Reset() {
	*x = GrpcPetriNet{}
	mi := &file_pm_models_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcPetriNet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPetriNet) ProtoMessage() {}

func (x *GrpcPetriNet) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPetriNet.ProtoReflect.Descriptor instead.
func (*GrpcPetriNet) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{8}
}

func (x *GrpcPetriNet) GetPlaces() []*GrpcPetriNetPlace {
	if x != nil {
		return x.Places
	}
	return nil
}

func (x *GrpcPetriNet) GetTransitions() []*GrpcPetriNetTransition {
	if x != nil {
		return x.Transitions
	}
	return nil
}

func (x *GrpcPetriNet) GetInitialMarking() *GrpcPetriNetMarking {
	if x != nil {
		return x.InitialMarking
	}
	return nil
}

func (x *GrpcPetriNet) GetFinalMarking() *GrpcPetriNetMarking {
	if x != nil {
		return x.FinalMarking
	}
	return nil
}

type GrpcPetriNetPlace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcPetriNetPlace) Reset() {
	*x = GrpcPetriNetPlace{}
	mi := &file_pm_models_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcPetriNetPlace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPetriNetPlace) ProtoMessage() {}

func (x *GrpcPetriNetPlace) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPetriNetPlace.ProtoReflect.Descriptor instead.
func (*GrpcPetriNetPlace) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{9}
}

func (x *GrpcPetriNetPlace) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GrpcPetriNetPlace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GrpcPetriNetTransition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IncomingArcs  []*GrpcPetriNetArc     `protobuf:"bytes,2,rep,name=incomingArcs,proto3" json:"incomingArcs,omitempty"`
	OutgoingArcs  []*GrpcPetriNetArc     `protobuf:"bytes,3,rep,name=outgoingArcs,proto3" json:"outgoingArcs,omitempty"`
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcPetriNetTransition) Reset() {
	*x = GrpcPetriNetTransition{}
	mi := &file_pm_models_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcPetriNetTransition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPetriNetTransition) ProtoMessage() {}

func (x *GrpcPetriNetTransition) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPetriNetTransition.ProtoReflect.Descriptor instead.
func (*GrpcPetriNetTransition) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{10}
}

func (x *GrpcPetriNetTransition) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GrpcPetriNetTransition) GetIncomingArcs() []*GrpcPetriNetArc {
	if x != nil {
		return x.IncomingArcs
	}
	return nil
}

func (x *GrpcPetriNetTransition) GetOutgoingArcs() []*GrpcPetriNetArc {
	if x != nil {
		return x.OutgoingArcs
	}
	return nil
}

func (x *GrpcPetriNetTransition) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type GrpcPetriNetArc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PlaceId       int64                  `protobuf:"varint,2,opt,name=placeId,proto3" json:"placeId,omitempty"`
	TokensCount   int64                  `protobuf:"varint,3,opt,name=tokens_count,json=tokensCount,proto3" json:"tokens_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcPetriNetArc) Reset() {
	*x = GrpcPetriNetArc{}
	mi := &file_pm_models_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcPetriNetArc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPetriNetArc) ProtoMessage() {}

func (x *GrpcPetriNetArc) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPetriNetArc.ProtoReflect.Descriptor instead.
func (*GrpcPetriNetArc) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{11}
}

func (x *GrpcPetriNetArc) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GrpcPetriNetArc) GetPlaceId() int64 {
	if x != nil {
		return x.PlaceId
	}
	return 0
}

func (x *GrpcPetriNetArc) GetTokensCount() int64 {
	if x != nil {
		return x.TokensCount
	}
	return 0
}

type GrpcPetriNetMarking struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Markings      []*GrpcPetriNetSinglePlaceMarking `protobuf:"bytes,1,rep,name=markings,proto3" json:"markings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcPetriNetMarking) Reset() {
	*x = GrpcPetriNetMarking{}
	mi := &file_pm_models_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcPetriNetMarking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPetriNetMarking) ProtoMessage() {}

func (x *GrpcPetriNetMarking) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPetriNetMarking.ProtoReflect.Descriptor instead.
func (*GrpcPetriNetMarking) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{12}
}

func (x *GrpcPetriNetMarking) GetMarkings() []*GrpcPetriNetSinglePlaceMarking {
	if x != nil {
		return x.Markings
	}
	return nil
}

type GrpcPetriNetSinglePlaceMarking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaceId       int64                  `protobuf:"varint,1,opt,name=placeId,proto3" json:"placeId,omitempty"`
	TokensCount   int64                  `protobuf:"varint,2,opt,name=tokensCount,proto3" json:"tokensCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcPetriNetSinglePlaceMarking) Reset() {
	*x = GrpcPetriNetSinglePlaceMarking{}
	mi := &file_pm_models_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcPetriNetSinglePlaceMarking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPetriNetSinglePlaceMarking) ProtoMessage() {}

func (x *GrpcPetriNetSinglePlaceMarking) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPetriNetSinglePlaceMarking.ProtoReflect.Descriptor instead.
func (*GrpcPetriNetSinglePlaceMarking) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{13}
}

func (x *GrpcPetriNetSinglePlaceMarking) GetPlaceId() int64 {
	if x != nil {
		return x.PlaceId
	}
	return 0
}

func (x *GrpcPetriNetSinglePlaceMarking) GetTokensCount() int64 {
	if x != nil {
		return x.TokensCount
	}
	return 0
}

type GrpcAnnotation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Annotation:
	//
	//	*GrpcAnnotation_CountAnnotation
	//	*GrpcAnnotation_FrequencyAnnotation
	//	*GrpcAnnotation_TimeAnnotation
	Annotation    isGrpcAnnotation_Annotation `protobuf_oneof:"annotation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcAnnotation) Reset() {
	*x = GrpcAnnotation{}
	mi := &file_pm_models_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcAnnotation) ProtoMessage() {}

func (x *GrpcAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcAnnotation.ProtoReflect.Descriptor instead.
func (*GrpcAnnotation) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{14}
}

func (x *GrpcAnnotation) GetAnnotation() isGrpcAnnotation_Annotation {
	if x != nil {
		return x.Annotation
	}
	return nil
}

func (x *GrpcAnnotation) GetCountAnnotation() *GrpcCountAnnotation {
	if x != nil {
		if x, ok := x.Annotation.(*GrpcAnnotation_CountAnnotation); ok {
			return x.CountAnnotation
		}
	}
	return nil
}

func (x *GrpcAnnotation) GetFrequencyAnnotation() *GrpcFrequenciesAnnotation {
	if x != nil {
		if x, ok := x.Annotation.(*GrpcAnnotation_FrequencyAnnotation); ok {
			return x.FrequencyAnnotation
		}
	}
	return nil
}

func (x *GrpcAnnotation) GetTimeAnnotation() *GrpcTimePerformanceAnnotation {
	if x != nil {
		if x, ok := x.Annotation.(*GrpcAnnotation_TimeAnnotation); ok {
			return x.TimeAnnotation
		}
	}
	return nil
}

type isGrpcAnnotation_Annotation interface {
	isGrpcAnnotation_Annotation()
}

type GrpcAnnotation_CountAnnotation struct {
	CountAnnotation *GrpcCountAnnotation `protobuf:"bytes,1,opt,name=countAnnotation,proto3,oneof"`
}

type GrpcAnnotation_FrequencyAnnotation struct {
	FrequencyAnnotation *GrpcFrequenciesAnnotation `protobuf:"bytes,2,opt,name=frequencyAnnotation,proto3,oneof"`
}

type GrpcAnnotation_TimeAnnotation struct {
	TimeAnnotation *GrpcTimePerformanceAnnotation `protobuf:"bytes,3,opt,name=timeAnnotation,proto3,oneof"`
}

func (*GrpcAnnotation_CountAnnotation) isGrpcAnnotation_Annotation() {}

func (*GrpcAnnotation_FrequencyAnnotation) isGrpcAnnotation_Annotation() {}

func (*GrpcAnnotation_TimeAnnotation) isGrpcAnnotation_Annotation() {}

type GrpcCountAnnotation struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Annotations   []*GrpcEntityCountAnnotation `protobuf:"bytes,1,rep,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcCountAnnotation) Reset() {
	*x = GrpcCountAnnotation{}
	mi := &file_pm_models_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcCountAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcCountAnnotation) ProtoMessage() {}

func (x *GrpcCountAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcCountAnnotation.ProtoReflect.Descriptor instead.
func (*GrpcCountAnnotation) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{15}
}

func (x *GrpcCountAnnotation) GetAnnotations() []*GrpcEntityCountAnnotation {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type GrpcEntityCountAnnotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      int64                  `protobuf:"varint,1,opt,name=entityId,proto3" json:"entityId,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcEntityCountAnnotation) Reset() {
	*x = GrpcEntityCountAnnotation{}
	mi := &file_pm_models_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcEntityCountAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcEntityCountAnnotation) ProtoMessage() {}

func (x *GrpcEntityCountAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcEntityCountAnnotation.ProtoReflect.Descriptor instead.
func (*GrpcEntityCountAnnotation) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{16}
}

func (x *GrpcEntityCountAnnotation) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *GrpcEntityCountAnnotation) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GrpcFrequenciesAnnotation struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Annotations   []*GrpcEntityFrequencyAnnotation `protobuf:"bytes,2,rep,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcFrequenciesAnnotation) Reset() {
	*x = GrpcFrequenciesAnnotation{}
	mi := &file_pm_models_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcFrequenciesAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcFrequenciesAnnotation) ProtoMessage() {}

func (x *GrpcFrequenciesAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcFrequenciesAnnotation.ProtoReflect.Descriptor instead.
func (*GrpcFrequenciesAnnotation) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{17}
}

func (x *GrpcFrequenciesAnnotation) GetAnnotations() []*GrpcEntityFrequencyAnnotation {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type GrpcEntityFrequencyAnnotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      int64                  `protobuf:"varint,1,opt,name=entityId,proto3" json:"entityId,omitempty"`
	Frequency     float32                `protobuf:"fixed32,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcEntityFrequencyAnnotation) Reset() {
	*x = GrpcEntityFrequencyAnnotation{}
	mi := &file_pm_models_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcEntityFrequencyAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcEntityFrequencyAnnotation) ProtoMessage() {}

func (x *GrpcEntityFrequencyAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcEntityFrequencyAnnotation.ProtoReflect.Descriptor instead.
func (*GrpcEntityFrequencyAnnotation) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{18}
}

func (x *GrpcEntityFrequencyAnnotation) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *GrpcEntityFrequencyAnnotation) GetFrequency() float32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

type GrpcTimePerformanceAnnotation struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Annotations   []*GrpcEntityTimeAnnotation `protobuf:"bytes,1,rep,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcTimePerformanceAnnotation) Reset() {
	*x = GrpcTimePerformanceAnnotation{}
	mi := &file_pm_models_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcTimePerformanceAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcTimePerformanceAnnotation) ProtoMessage() {}

func (x *GrpcTimePerformanceAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcTimePerformanceAnnotation.ProtoReflect.Descriptor instead.
func (*GrpcTimePerformanceAnnotation) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{19}
}

func (x *GrpcTimePerformanceAnnotation) GetAnnotations() []*GrpcEntityTimeAnnotation {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type GrpcEntityTimeAnnotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      int64                  `protobuf:"varint,1,opt,name=entityId,proto3" json:"entityId,omitempty"`
	Interval      *GrpcTimeSpan          `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcEntityTimeAnnotation) Reset() {
	*x = GrpcEntityTimeAnnotation{}
	mi := &file_pm_models_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcEntityTimeAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcEntityTimeAnnotation) ProtoMessage() {}

func (x *GrpcEntityTimeAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcEntityTimeAnnotation.ProtoReflect.Descriptor instead.
func (*GrpcEntityTimeAnnotation) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{20}
}

func (x *GrpcEntityTimeAnnotation) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *GrpcEntityTimeAnnotation) GetInterval() *GrpcTimeSpan {
	if x != nil {
		return x.Interval
	}
	return nil
}

type GrpcMatrix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*GrpcMatrixRow       `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcMatrix) Reset() {
	*x = GrpcMatrix{}
	mi := &file_pm_models_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcMatrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcMatrix) ProtoMessage() {}

func (x *GrpcMatrix) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcMatrix.ProtoReflect.Descriptor instead.
func (*GrpcMatrix) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{21}
}

func (x *GrpcMatrix) GetRows() []*GrpcMatrixRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type GrpcMatrixRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcMatrixRow) Reset() {
	*x = GrpcMatrixRow{}
	mi := &file_pm_models_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcMatrixRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcMatrixRow) ProtoMessage() {}

func (x *GrpcMatrixRow) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcMatrixRow.ProtoReflect.Descriptor instead.
func (*GrpcMatrixRow) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{22}
}

func (x *GrpcMatrixRow) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type GrpcDataset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matrix        *GrpcMatrix            `protobuf:"bytes,1,opt,name=matrix,proto3" json:"matrix,omitempty"`
	ColumnsNames  []string               `protobuf:"bytes,2,rep,name=columnsNames,proto3" json:"columnsNames,omitempty"`
	RowNames      []string               `protobuf:"bytes,3,rep,name=rowNames,proto3" json:"rowNames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcDataset) Reset() {
	*x = GrpcDataset{}
	mi := &file_pm_models_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcDataset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcDataset) ProtoMessage() {}

func (x *GrpcDataset) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcDataset.ProtoReflect.Descriptor instead.
func (*GrpcDataset) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{23}
}

func (x *GrpcDataset) GetMatrix() *GrpcMatrix {
	if x != nil {
		return x.Matrix
	}
	return nil
}

func (x *GrpcDataset) GetColumnsNames() []string {
	if x != nil {
		return x.ColumnsNames
	}
	return nil
}

func (x *GrpcDataset) GetRowNames() []string {
	if x != nil {
		return x.RowNames
	}
	return nil
}

type GrpcLabeledDataset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dataset       *GrpcDataset           `protobuf:"bytes,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Labels        []int32                `protobuf:"varint,2,rep,packed,name=labels,proto3" json:"labels,omitempty"`
	LabelsColors  []*GrpcColor           `protobuf:"bytes,3,rep,name=labelsColors,proto3" json:"labelsColors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcLabeledDataset) Reset() {
	*x = GrpcLabeledDataset{}
	mi := &file_pm_models_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcLabeledDataset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcLabeledDataset) ProtoMessage() {}

func (x *GrpcLabeledDataset) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcLabeledDataset.ProtoReflect.Descriptor instead.
func (*GrpcLabeledDataset) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{24}
}

func (x *GrpcLabeledDataset) GetDataset() *GrpcDataset {
	if x != nil {
		return x.Dataset
	}
	return nil
}

func (x *GrpcLabeledDataset) GetLabels() []int32 {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *GrpcLabeledDataset) GetLabelsColors() []*GrpcColor {
	if x != nil {
		return x.LabelsColors
	}
	return nil
}

var File_pm_models_proto protoreflect.FileDescriptor

const file_pm_models_proto_rawDesc = "" +
	"\n" +
	"\x0fpm_models.proto\x12\x05ficus\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\n" +
	"util.proto\"D\n" +
	"\x12GrpcSimpleEventLog\x12.\n" +
	"\x06traces\x18\x01 \x03(\v2\x16.ficus.GrpcSimpleTraceR\x06traces\";\n" +
	"\x0fGrpcSimpleTrace\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.ficus.GrpcEventR\x06events\"\x8c\x01\n" +
	"\tGrpcEvent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x05stamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05stamp\x129\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2\x19.ficus.GrpcEventAttributeR\n" +
	"attributes\"\xac\x02\n" +
	"\x12GrpcEventAttribute\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x03int\x18\x02 \x01(\x03H\x00R\x03int\x12\x18\n" +
	"\x06string\x18\x03 \x01(\tH\x00R\x06string\x12\x14\n" +
	"\x04bool\x18\x04 \x01(\bH\x00R\x04bool\x12\x18\n" +
	"\x06double\x18\x05 \x01(\x01H\x00R\x06double\x12%\n" +
	"\x04guid\x18\x06 \x01(\v2\x0f.ficus.GrpcGuidH\x00R\x04guid\x12,\n" +
	"\x04null\x18\a \x01(\v2\x16.google.protobuf.EmptyH\x00R\x04null\x122\n" +
	"\x05stamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x05stamp\x12\x14\n" +
	"\x04uint\x18\t \x01(\x04H\x00R\x04uintB\a\n" +
	"\x05value\"G\n" +
	"\x12GrpcHashesEventLog\x121\n" +
	"\x06traces\x18\x02 \x03(\v2\x19.ficus.GrpcHashesLogTraceR\x06traces\",\n" +
	"\x12GrpcHashesLogTrace\x12\x16\n" +
	"\x06events\x18\x01 \x03(\x04R\x06events\"B\n" +
	"\x11GrpcNamesEventLog\x12-\n" +
	"\x06traces\x18\x01 \x03(\v2\x15.ficus.GrpcNamesTraceR\x06traces\"(\n" +
	"\x0eGrpcNamesTrace\x12\x16\n" +
	"\x06events\x18\x01 \x03(\tR\x06events\"\x87\x02\n" +
	"\fGrpcPetriNet\x120\n" +
	"\x06places\x18\x01 \x03(\v2\x18.ficus.GrpcPetriNetPlaceR\x06places\x12?\n" +
	"\vtransitions\x18\x02 \x03(\v2\x1d.ficus.GrpcPetriNetTransitionR\vtransitions\x12C\n" +
	"\x0finitial_marking\x18\x03 \x01(\v2\x1a.ficus.GrpcPetriNetMarkingR\x0einitialMarking\x12?\n" +
	"\rfinal_marking\x18\x04 \x01(\v2\x1a.ficus.GrpcPetriNetMarkingR\ffinalMarking\"7\n" +
	"\x11GrpcPetriNetPlace\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xb4\x01\n" +
	"\x16GrpcPetriNetTransition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12:\n" +
	"\fincomingArcs\x18\x02 \x03(\v2\x16.ficus.GrpcPetriNetArcR\fincomingArcs\x12:\n" +
	"\foutgoingArcs\x18\x03 \x03(\v2\x16.ficus.GrpcPetriNetArcR\foutgoingArcs\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\"^\n" +
	"\x0fGrpcPetriNetArc\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aplaceId\x18\x02 \x01(\x03R\aplaceId\x12!\n" +
	"\ftokens_count\x18\x03 \x01(\x03R\vtokensCount\"X\n" +
	"\x13GrpcPetriNetMarking\x12A\n" +
	"\bmarkings\x18\x01 \x03(\v2%.ficus.GrpcPetriNetSinglePlaceMarkingR\bmarkings\"\\\n" +
	"\x1eGrpcPetriNetSinglePlaceMarking\x12\x18\n" +
	"\aplaceId\x18\x01 \x01(\x03R\aplaceId\x12 \n" +
	"\vtokensCount\x18\x02 \x01(\x03R\vtokensCount\"\x8c\x02\n" +
	"\x0eGrpcAnnotation\x12F\n" +
	"\x0fcountAnnotation\x18\x01 \x01(\v2\x1a.ficus.GrpcCountAnnotationH\x00R\x0fcountAnnotation\x12T\n" +
	"\x13frequencyAnnotation\x18\x02 \x01(\v2 .ficus.GrpcFrequenciesAnnotationH\x00R\x13frequencyAnnotation\x12N\n" +
	"\x0etimeAnnotation\x18\x03 \x01(\v2$.ficus.GrpcTimePerformanceAnnotationH\x00R\x0etimeAnnotationB\f\n" +
	"\n" +
	"annotation\"Y\n" +
	"\x13GrpcCountAnnotation\x12B\n" +
	"\vannotations\x18\x01 \x03(\v2 .ficus.GrpcEntityCountAnnotationR\vannotations\"M\n" +
	"\x19GrpcEntityCountAnnotation\x12\x1a\n" +
	"\bentityId\x18\x01 \x01(\x03R\bentityId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"c\n" +
	"\x19GrpcFrequenciesAnnotation\x12F\n" +
	"\vannotations\x18\x02 \x03(\v2$.ficus.GrpcEntityFrequencyAnnotationR\vannotations\"Y\n" +
	"\x1dGrpcEntityFrequencyAnnotation\x12\x1a\n" +
	"\bentityId\x18\x01 \x01(\x03R\bentityId\x12\x1c\n" +
	"\tfrequency\x18\x02 \x01(\x02R\tfrequency\"b\n" +
	"\x1dGrpcTimePerformanceAnnotation\x12A\n" +
	"\vannotations\x18\x01 \x03(\v2\x1f.ficus.GrpcEntityTimeAnnotationR\vannotations\"g\n" +
	"\x18GrpcEntityTimeAnnotation\x12\x1a\n" +
	"\bentityId\x18\x01 \x01(\x03R\bentityId\x12/\n" +
	"\binterval\x18\x02 \x01(\v2\x13.ficus.GrpcTimeSpanR\binterval\"6\n" +
	"\n" +
	"GrpcMatrix\x12(\n" +
	"\x04rows\x18\x01 \x03(\v2\x14.ficus.GrpcMatrixRowR\x04rows\"'\n" +
	"\rGrpcMatrixRow\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"x\n" +
	"\vGrpcDataset\x12)\n" +
	"\x06matrix\x18\x01 \x01(\v2\x11.ficus.GrpcMatrixR\x06matrix\x12\"\n" +
	"\fcolumnsNames\x18\x02 \x03(\tR\fcolumnsNames\x12\x1a\n" +
	"\browNames\x18\x03 \x03(\tR\browNames\"\x90\x01\n" +
	"\x12GrpcLabeledDataset\x12,\n" +
	"\adataset\x18\x01 \x01(\v2\x12.ficus.GrpcDatasetR\adataset\x12\x16\n" +
	"\x06labels\x18\x02 \x03(\x05R\x06labels\x124\n" +
	"\flabelsColors\x18\x03 \x03(\v2\x10.ficus.GrpcColorR\flabelsColorsB\x0fZ\r./;grpcmodelsb\x06proto3"

var (
	file_pm_models_proto_rawDescOnce sync.Once
	file_pm_models_proto_rawDescData []byte
)

func file_pm_models_proto_rawDescGZIP() []byte {
	file_pm_models_proto_rawDescOnce.Do(func() {
		file_pm_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pm_models_proto_rawDesc), len(file_pm_models_proto_rawDesc)))
	})
	return file_pm_models_proto_rawDescData
}

var file_pm_models_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_pm_models_proto_goTypes = []any{
	(*GrpcSimpleEventLog)(nil),             // 0: ficus.GrpcSimpleEventLog
	(*GrpcSimpleTrace)(nil),                // 1: ficus.GrpcSimpleTrace
	(*GrpcEvent)(nil),                      // 2: ficus.GrpcEvent
	(*GrpcEventAttribute)(nil),             // 3: ficus.GrpcEventAttribute
	(*GrpcHashesEventLog)(nil),             // 4: ficus.GrpcHashesEventLog
	(*GrpcHashesLogTrace)(nil),             // 5: ficus.GrpcHashesLogTrace
	(*GrpcNamesEventLog)(nil),              // 6: ficus.GrpcNamesEventLog
	(*GrpcNamesTrace)(nil),                 // 7: ficus.GrpcNamesTrace
	(*GrpcPetriNet)(nil),                   // 8: ficus.GrpcPetriNet
	(*GrpcPetriNetPlace)(nil),              // 9: ficus.GrpcPetriNetPlace
	(*GrpcPetriNetTransition)(nil),         // 10: ficus.GrpcPetriNetTransition
	(*GrpcPetriNetArc)(nil),                // 11: ficus.GrpcPetriNetArc
	(*GrpcPetriNetMarking)(nil),            // 12: ficus.GrpcPetriNetMarking
	(*GrpcPetriNetSinglePlaceMarking)(nil), // 13: ficus.GrpcPetriNetSinglePlaceMarking
	(*GrpcAnnotation)(nil),                 // 14: ficus.GrpcAnnotation
	(*GrpcCountAnnotation)(nil),            // 15: ficus.GrpcCountAnnotation
	(*GrpcEntityCountAnnotation)(nil),      // 16: ficus.GrpcEntityCountAnnotation
	(*GrpcFrequenciesAnnotation)(nil),      // 17: ficus.GrpcFrequenciesAnnotation
	(*GrpcEntityFrequencyAnnotation)(nil),  // 18: ficus.GrpcEntityFrequencyAnnotation
	(*GrpcTimePerformanceAnnotation)(nil),  // 19: ficus.GrpcTimePerformanceAnnotation
	(*GrpcEntityTimeAnnotation)(nil),       // 20: ficus.GrpcEntityTimeAnnotation
	(*GrpcMatrix)(nil),                     // 21: ficus.GrpcMatrix
	(*GrpcMatrixRow)(nil),                  // 22: ficus.GrpcMatrixRow
	(*GrpcDataset)(nil),                    // 23: ficus.GrpcDataset
	(*GrpcLabeledDataset)(nil),             // 24: ficus.GrpcLabeledDataset
	(*timestamppb.Timestamp)(nil),          // 25: google.protobuf.Timestamp
	(*GrpcGuid)(nil),                       // 26: ficus.GrpcGuid
	(*emptypb.Empty)(nil),                  // 27: google.protobuf.Empty
	(*GrpcTimeSpan)(nil),                   // 28: ficus.GrpcTimeSpan
	(*GrpcColor)(nil),                      // 29: ficus.GrpcColor
}
var file_pm_models_proto_depIdxs = []int32{
	1,  // 0: ficus.GrpcSimpleEventLog.traces:type_name -> ficus.GrpcSimpleTrace
	2,  // 1: ficus.GrpcSimpleTrace.events:type_name -> ficus.GrpcEvent
	25, // 2: ficus.GrpcEvent.stamp:type_name -> google.protobuf.Timestamp
	3,  // 3: ficus.GrpcEvent.attributes:type_name -> ficus.GrpcEventAttribute
	26, // 4: ficus.GrpcEventAttribute.guid:type_name -> ficus.GrpcGuid
	27, // 5: ficus.GrpcEventAttribute.null:type_name -> google.protobuf.Empty
	25, // 6: ficus.GrpcEventAttribute.stamp:type_name -> google.protobuf.Timestamp
	5,  // 7: ficus.GrpcHashesEventLog.traces:type_name -> ficus.GrpcHashesLogTrace
	7,  // 8: ficus.GrpcNamesEventLog.traces:type_name -> ficus.GrpcNamesTrace
	9,  // 9: ficus.GrpcPetriNet.places:type_name -> ficus.GrpcPetriNetPlace
	10, // 10: ficus.GrpcPetriNet.transitions:type_name -> ficus.GrpcPetriNetTransition
	12, // 11: ficus.GrpcPetriNet.initial_marking:type_name -> ficus.GrpcPetriNetMarking
	12, // 12: ficus.GrpcPetriNet.final_marking:type_name -> ficus.GrpcPetriNetMarking
	11, // 13: ficus.GrpcPetriNetTransition.incomingArcs:type_name -> ficus.GrpcPetriNetArc
	11, // 14: ficus.GrpcPetriNetTransition.outgoingArcs:type_name -> ficus.GrpcPetriNetArc
	13, // 15: ficus.GrpcPetriNetMarking.markings:type_name -> ficus.GrpcPetriNetSinglePlaceMarking
	15, // 16: ficus.GrpcAnnotation.countAnnotation:type_name -> ficus.GrpcCountAnnotation
	17, // 17: ficus.GrpcAnnotation.frequencyAnnotation:type_name -> ficus.GrpcFrequenciesAnnotation
	19, // 18: ficus.GrpcAnnotation.timeAnnotation:type_name -> ficus.GrpcTimePerformanceAnnotation
	16, // 19: ficus.GrpcCountAnnotation.annotations:type_name -> ficus.GrpcEntityCountAnnotation
	18, // 20: ficus.GrpcFrequenciesAnnotation.annotations:type_name -> ficus.GrpcEntityFrequencyAnnotation
	20, // 21: ficus.GrpcTimePerformanceAnnotation.annotations:type_name -> ficus.GrpcEntityTimeAnnotation
	28, // 22: ficus.GrpcEntityTimeAnnotation.interval:type_name -> ficus.GrpcTimeSpan
	22, // 23: ficus.GrpcMatrix.rows:type_name -> ficus.GrpcMatrixRow
	21, // 24: ficus.GrpcDataset.matrix:type_name -> ficus.GrpcMatrix
	23, // 25: ficus.GrpcLabeledDataset.dataset:type_name -> ficus.GrpcDataset
	29, // 26: ficus.GrpcLabeledDataset.labelsColors:type_name -> ficus.GrpcColor
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_pm_models_proto_init() }
func file_pm_models_proto_init() {
	if File_pm_models_proto != nil {
		return
	}
	file_util_proto_init()
	file_pm_models_proto_msgTypes[3].OneofWrappers = []any{
		(*GrpcEventAttribute_Int)(nil),
		(*GrpcEventAttribute_String_)(nil),
		(*GrpcEventAttribute_Bool)(nil),
		(*GrpcEventAttribute_Double)(nil),
		(*GrpcEventAttribute_Guid)(nil),
		(*GrpcEventAttribute_Null)(nil),
		(*GrpcEventAttribute_Stamp)(nil),
		(*GrpcEventAttribute_Uint)(nil),
	}
	file_pm_models_proto_msgTypes[14].OneofWrappers = []any{
		(*GrpcAnnotation_CountAnnotation)(nil),
		(*GrpcAnnotation_FrequencyAnnotation)(nil),
		(*GrpcAnnotation_TimeAnnotation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pm_models_proto_rawDesc), len(file_pm_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pm_models_proto_goTypes,
		DependencyIndexes: file_pm_models_proto_depIdxs,
		MessageInfos:      file_pm_models_proto_msgTypes,
	}.Build()
	File_pm_models_proto = out.File
	file_pm_models_proto_goTypes = nil
	file_pm_models_proto_depIdxs = nil
}
