# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!

"""Client and server classes corresponding to protobuf-defined services."""

import grpc



import ficus.grpc_pipelines.models.context_values_service_pb2 as context__values__service__pb2

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

import ficus.grpc_pipelines.models.util_pb2 as util__pb2





class GrpcContextValuesServiceStub(object):

    """Missing associated documentation comment in .proto file."""



    def __init__(self, channel):

        """Constructor.



        Args:

            channel: A grpc.Channel.

        """

        self.SetContextValue = channel.stream_unary(

                '/ficus.GrpcContextValuesService/SetContextValue',

                request_serializer=context__values__service__pb2.GrpcContextValuePart.SerializeToString,

                response_deserializer=util__pb2.GrpcGuid.FromString,

                )

        self.DropContextValues = channel.unary_unary(

                '/ficus.GrpcContextValuesService/DropContextValues',

                request_serializer=context__values__service__pb2.GrpcDropContextValuesRequest.SerializeToString,

                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,

                )





class GrpcContextValuesServiceServicer(object):

    """Missing associated documentation comment in .proto file."""



    def SetContextValue(self, request_iterator, context):

        """Missing associated documentation comment in .proto file."""

        context.set_code(grpc.StatusCode.UNIMPLEMENTED)

        context.set_details('Method not implemented!')

        raise NotImplementedError('Method not implemented!')



    def DropContextValues(self, request, context):

        """Missing associated documentation comment in .proto file."""

        context.set_code(grpc.StatusCode.UNIMPLEMENTED)

        context.set_details('Method not implemented!')

        raise NotImplementedError('Method not implemented!')





def add_GrpcContextValuesServiceServicer_to_server(servicer, server):

    rpc_method_handlers = {

            'SetContextValue': grpc.stream_unary_rpc_method_handler(

                    servicer.SetContextValue,

                    request_deserializer=context__values__service__pb2.GrpcContextValuePart.FromString,

                    response_serializer=util__pb2.GrpcGuid.SerializeToString,

            ),

            'DropContextValues': grpc.unary_unary_rpc_method_handler(

                    servicer.DropContextValues,

                    request_deserializer=context__values__service__pb2.GrpcDropContextValuesRequest.FromString,

                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,

            ),

    }

    generic_handler = grpc.method_handlers_generic_handler(

            'ficus.GrpcContextValuesService', rpc_method_handlers)

    server.add_generic_rpc_handlers((generic_handler,))





 # This class is part of an EXPERIMENTAL API.

class GrpcContextValuesService(object):

    """Missing associated documentation comment in .proto file."""



    @staticmethod

    def SetContextValue(request_iterator,

            target,

            options=(),

            channel_credentials=None,

            call_credentials=None,

            insecure=False,

            compression=None,

            wait_for_ready=None,

            timeout=None,

            metadata=None):

        return grpc.experimental.stream_unary(request_iterator, target, '/ficus.GrpcContextValuesService/SetContextValue',

            context__values__service__pb2.GrpcContextValuePart.SerializeToString,

            util__pb2.GrpcGuid.FromString,

            options, channel_credentials,

            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)



    @staticmethod

    def DropContextValues(request,

            target,

            options=(),

            channel_credentials=None,

            call_credentials=None,

            insecure=False,

            compression=None,

            wait_for_ready=None,

            timeout=None,

            metadata=None):

        return grpc.experimental.unary_unary(request, target, '/ficus.GrpcContextValuesService/DropContextValues',

            context__values__service__pb2.GrpcDropContextValuesRequest.SerializeToString,

            google_dot_protobuf_dot_empty__pb2.Empty.FromString,

            options, channel_credentials,

            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
