# -*- coding: utf-8 -*-

# Generated by the protocol buffer compiler.  DO NOT EDIT!

# source: context_values_service.proto

"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor

from google.protobuf import descriptor_pool as _descriptor_pool

from google.protobuf import symbol_database as _symbol_database

from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)



_sym_db = _symbol_database.Default()





import ficus.grpc_pipelines.models.pipelines_and_context_pb2 as pipelines__and__context__pb2

import ficus.grpc_pipelines.models.util_pb2 as util__pb2

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2





DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63ontext_values_service.proto\x12\x05\x66icus\x1a\x1bpipelines_and_context.proto\x1a\nutil.proto\x1a\x1bgoogle/protobuf/empty.proto\"2\n\x14GrpcContextValuePart\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05\x62ytes\x18\x03 \x01(\x0c\"<\n\x1cGrpcDropContextValuesRequest\x12\x1c\n\x03ids\x18\x01 \x03(\x0b\x32\x0f.ficus.GrpcGuid2\xaf\x01\n\x18GrpcContextValuesService\x12\x41\n\x0fSetContextValue\x12\x1b.ficus.GrpcContextValuePart\x1a\x0f.ficus.GrpcGuid(\x01\x12P\n\x11\x44ropContextValues\x12#.ficus.GrpcDropContextValuesRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')



_globals = globals()

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)

_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'context_values_service_pb2', _globals)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None

  _globals['_GRPCCONTEXTVALUEPART']._serialized_start=109

  _globals['_GRPCCONTEXTVALUEPART']._serialized_end=159

  _globals['_GRPCDROPCONTEXTVALUESREQUEST']._serialized_start=161

  _globals['_GRPCDROPCONTEXTVALUESREQUEST']._serialized_end=221

  _globals['_GRPCCONTEXTVALUESSERVICE']._serialized_start=224

  _globals['_GRPCCONTEXTVALUESSERVICE']._serialized_end=399

# @@protoc_insertion_point(module_scope)
