# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!

"""Client and server classes corresponding to protobuf-defined services."""

import grpc



import ficus.grpc_pipelines.models.front_contract_pb2 as front__contract__pb2

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2





class GrpcKafkaUpdatesProcessorStub(object):

    """Missing associated documentation comment in .proto file."""



    def __init__(self, channel):

        """Constructor.



        Args:

            channel: A grpc.Channel.

        """

        self.GetCurrentCases = channel.unary_unary(

                '/ficus.GrpcKafkaUpdatesProcessor/GetCurrentCases',

                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,

                response_deserializer=front__contract__pb2.GrpcCurrentCasesResponse.FromString,

                )

        self.StartUpdatesStream = channel.stream_unary(

                '/ficus.GrpcKafkaUpdatesProcessor/StartUpdatesStream',

                request_serializer=front__contract__pb2.GrpcKafkaUpdate.SerializeToString,

                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,

                )





class GrpcKafkaUpdatesProcessorServicer(object):

    """Missing associated documentation comment in .proto file."""



    def GetCurrentCases(self, request, context):

        """Missing associated documentation comment in .proto file."""

        context.set_code(grpc.StatusCode.UNIMPLEMENTED)

        context.set_details('Method not implemented!')

        raise NotImplementedError('Method not implemented!')



    def StartUpdatesStream(self, request_iterator, context):

        """Missing associated documentation comment in .proto file."""

        context.set_code(grpc.StatusCode.UNIMPLEMENTED)

        context.set_details('Method not implemented!')

        raise NotImplementedError('Method not implemented!')





def add_GrpcKafkaUpdatesProcessorServicer_to_server(servicer, server):

    rpc_method_handlers = {

            'GetCurrentCases': grpc.unary_unary_rpc_method_handler(

                    servicer.GetCurrentCases,

                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,

                    response_serializer=front__contract__pb2.GrpcCurrentCasesResponse.SerializeToString,

            ),

            'StartUpdatesStream': grpc.stream_unary_rpc_method_handler(

                    servicer.StartUpdatesStream,

                    request_deserializer=front__contract__pb2.GrpcKafkaUpdate.FromString,

                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,

            ),

    }

    generic_handler = grpc.method_handlers_generic_handler(

            'ficus.GrpcKafkaUpdatesProcessor', rpc_method_handlers)

    server.add_generic_rpc_handlers((generic_handler,))





 # This class is part of an EXPERIMENTAL API.

class GrpcKafkaUpdatesProcessor(object):

    """Missing associated documentation comment in .proto file."""



    @staticmethod

    def GetCurrentCases(request,

            target,

            options=(),

            channel_credentials=None,

            call_credentials=None,

            insecure=False,

            compression=None,

            wait_for_ready=None,

            timeout=None,

            metadata=None):

        return grpc.experimental.unary_unary(request, target, '/ficus.GrpcKafkaUpdatesProcessor/GetCurrentCases',

            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,

            front__contract__pb2.GrpcCurrentCasesResponse.FromString,

            options, channel_credentials,

            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)



    @staticmethod

    def StartUpdatesStream(request_iterator,

            target,

            options=(),

            channel_credentials=None,

            call_credentials=None,

            insecure=False,

            compression=None,

            wait_for_ready=None,

            timeout=None,

            metadata=None):

        return grpc.experimental.stream_unary(request_iterator, target, '/ficus.GrpcKafkaUpdatesProcessor/StartUpdatesStream',

            front__contract__pb2.GrpcKafkaUpdate.SerializeToString,

            google_dot_protobuf_dot_empty__pb2.Empty.FromString,

            options, channel_credentials,

            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
