# -*- coding: utf-8 -*-

# Generated by the protocol buffer compiler.  DO NOT EDIT!

# source: front_contract.proto

"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor

from google.protobuf import descriptor_pool as _descriptor_pool

from google.protobuf import symbol_database as _symbol_database

from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)



_sym_db = _symbol_database.Default()





import ficus.grpc_pipelines.models.pipelines_and_context_pb2 as pipelines__and__context__pb2

import ficus.grpc_pipelines.models.util_pb2 as util__pb2

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2





DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66ront_contract.proto\x12\x05\x66icus\x1a\x1bpipelines_and_context.proto\x1a\nutil.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x01\n\x16GrpcPipelinePartUpdate\x12\x38\n\rcurrent_cases\x18\x01 \x01(\x0b\x32\x1f.ficus.GrpcCurrentCasesResponseH\x00\x12\'\n\x05\x64\x65lta\x18\x02 \x01(\x0b\x32\x16.ficus.GrpcKafkaUpdateH\x00\x42\x08\n\x06update\"\xaa\x01\n\x0fGrpcKafkaUpdate\x12\x13\n\x0bprocessName\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61seName\x18\x02 \x01(\t\x12\x35\n\x10pipelinePartInfo\x18\x03 \x01(\x0b\x32\x1b.ficus.GrpcPipelinePartInfo\x12\x39\n\rcontextValues\x18\x04 \x03(\x0b\x32\".ficus.GrpcContextValueWithKeyName\":\n\x18GrpcCurrentCasesResponse\x12\x1e\n\x05\x63\x61ses\x18\x01 \x03(\x0b\x32\x0f.ficus.GrpcCase\"Y\n\x08GrpcCase\x12\x10\n\x08\x63\x61seName\x18\x01 \x01(\t\x12;\n\rcontextValues\x18\x02 \x03(\x0b\x32$.ficus.GrpcPipelinePartContextValues\"\xbc\x01\n\x1dGrpcPipelinePartContextValues\x12\x35\n\x10pipelinePartInfo\x18\x01 \x01(\x0b\x32\x1b.ficus.GrpcPipelinePartInfo\x12)\n\x05stamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x39\n\rcontextValues\x18\x03 \x03(\x0b\x32\".ficus.GrpcContextValueWithKeyName\"A\n\x14GrpcPipelinePartInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1b\n\x02id\x18\x02 \x01(\x0b\x32\x0f.ficus.GrpcGuid2v\n%GrpcPipelinePartsContextValuesService\x12M\n\x12StartUpdatesStream\x12\x16.google.protobuf.Empty\x1a\x1d.ficus.GrpcPipelinePartUpdate0\x01\x62\x06proto3')



_globals = globals()

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)

_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'front_contract_pb2', _globals)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None

  _globals['_GRPCPIPELINEPARTUPDATE']._serialized_start=135

  _globals['_GRPCPIPELINEPARTUPDATE']._serialized_end=268

  _globals['_GRPCKAFKAUPDATE']._serialized_start=271

  _globals['_GRPCKAFKAUPDATE']._serialized_end=441

  _globals['_GRPCCURRENTCASESRESPONSE']._serialized_start=443

  _globals['_GRPCCURRENTCASESRESPONSE']._serialized_end=501

  _globals['_GRPCCASE']._serialized_start=503

  _globals['_GRPCCASE']._serialized_end=592

  _globals['_GRPCPIPELINEPARTCONTEXTVALUES']._serialized_start=595

  _globals['_GRPCPIPELINEPARTCONTEXTVALUES']._serialized_end=783

  _globals['_GRPCPIPELINEPARTINFO']._serialized_start=785

  _globals['_GRPCPIPELINEPARTINFO']._serialized_end=850

  _globals['_GRPCPIPELINEPARTSCONTEXTVALUESSERVICE']._serialized_start=852

  _globals['_GRPCPIPELINEPARTSCONTEXTVALUESSERVICE']._serialized_end=970

# @@protoc_insertion_point(module_scope)
