# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!

"""Client and server classes corresponding to protobuf-defined services."""

import grpc



from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

import ficus.grpc_pipelines.models.kafka_service_pb2 as kafka__service__pb2





class GrpcKafkaServiceStub(object):

    """Missing associated documentation comment in .proto file."""



    def __init__(self, channel):

        """Constructor.



        Args:

            channel: A grpc.Channel.

        """

        self.SubscribeForKafkaTopic = channel.unary_unary(

                '/ficus.GrpcKafkaService/SubscribeForKafkaTopic',

                request_serializer=kafka__service__pb2.GrpcSubscribeForKafkaTopicRequest.SerializeToString,

                response_deserializer=kafka__service__pb2.GrpcKafkaResult.FromString,

                )

        self.UnsubscribeFromKafkaTopic = channel.unary_unary(

                '/ficus.GrpcKafkaService/UnsubscribeFromKafkaTopic',

                request_serializer=kafka__service__pb2.GrpcUnsubscribeFromKafkaRequest.SerializeToString,

                response_deserializer=kafka__service__pb2.GrpcKafkaResult.FromString,

                )





class GrpcKafkaServiceServicer(object):

    """Missing associated documentation comment in .proto file."""



    def SubscribeForKafkaTopic(self, request, context):

        """Missing associated documentation comment in .proto file."""

        context.set_code(grpc.StatusCode.UNIMPLEMENTED)

        context.set_details('Method not implemented!')

        raise NotImplementedError('Method not implemented!')



    def UnsubscribeFromKafkaTopic(self, request, context):

        """Missing associated documentation comment in .proto file."""

        context.set_code(grpc.StatusCode.UNIMPLEMENTED)

        context.set_details('Method not implemented!')

        raise NotImplementedError('Method not implemented!')





def add_GrpcKafkaServiceServicer_to_server(servicer, server):

    rpc_method_handlers = {

            'SubscribeForKafkaTopic': grpc.unary_unary_rpc_method_handler(

                    servicer.SubscribeForKafkaTopic,

                    request_deserializer=kafka__service__pb2.GrpcSubscribeForKafkaTopicRequest.FromString,

                    response_serializer=kafka__service__pb2.GrpcKafkaResult.SerializeToString,

            ),

            'UnsubscribeFromKafkaTopic': grpc.unary_unary_rpc_method_handler(

                    servicer.UnsubscribeFromKafkaTopic,

                    request_deserializer=kafka__service__pb2.GrpcUnsubscribeFromKafkaRequest.FromString,

                    response_serializer=kafka__service__pb2.GrpcKafkaResult.SerializeToString,

            ),

    }

    generic_handler = grpc.method_handlers_generic_handler(

            'ficus.GrpcKafkaService', rpc_method_handlers)

    server.add_generic_rpc_handlers((generic_handler,))





 # This class is part of an EXPERIMENTAL API.

class GrpcKafkaService(object):

    """Missing associated documentation comment in .proto file."""



    @staticmethod

    def SubscribeForKafkaTopic(request,

            target,

            options=(),

            channel_credentials=None,

            call_credentials=None,

            insecure=False,

            compression=None,

            wait_for_ready=None,

            timeout=None,

            metadata=None):

        return grpc.experimental.unary_unary(request, target, '/ficus.GrpcKafkaService/SubscribeForKafkaTopic',

            kafka__service__pb2.GrpcSubscribeForKafkaTopicRequest.SerializeToString,

            kafka__service__pb2.GrpcKafkaResult.FromString,

            options, channel_credentials,

            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)



    @staticmethod

    def UnsubscribeFromKafkaTopic(request,

            target,

            options=(),

            channel_credentials=None,

            call_credentials=None,

            insecure=False,

            compression=None,

            wait_for_ready=None,

            timeout=None,

            metadata=None):

        return grpc.experimental.unary_unary(request, target, '/ficus.GrpcKafkaService/UnsubscribeFromKafkaTopic',

            kafka__service__pb2.GrpcUnsubscribeFromKafkaRequest.SerializeToString,

            kafka__service__pb2.GrpcKafkaResult.FromString,

            options, channel_credentials,

            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)





class GrpcKafkaUpdatesProcessorStub(object):

    """Missing associated documentation comment in .proto file."""



    def __init__(self, channel):

        """Constructor.



        Args:

            channel: A grpc.Channel.

        """

        self.StartUpdatesStream = channel.stream_unary(

                '/ficus.GrpcKafkaUpdatesProcessor/StartUpdatesStream',

                request_serializer=kafka__service__pb2.GrpcKafkaUpdate.SerializeToString,

                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,

                )





class GrpcKafkaUpdatesProcessorServicer(object):

    """Missing associated documentation comment in .proto file."""



    def StartUpdatesStream(self, request_iterator, context):

        """Missing associated documentation comment in .proto file."""

        context.set_code(grpc.StatusCode.UNIMPLEMENTED)

        context.set_details('Method not implemented!')

        raise NotImplementedError('Method not implemented!')





def add_GrpcKafkaUpdatesProcessorServicer_to_server(servicer, server):

    rpc_method_handlers = {

            'StartUpdatesStream': grpc.stream_unary_rpc_method_handler(

                    servicer.StartUpdatesStream,

                    request_deserializer=kafka__service__pb2.GrpcKafkaUpdate.FromString,

                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,

            ),

    }

    generic_handler = grpc.method_handlers_generic_handler(

            'ficus.GrpcKafkaUpdatesProcessor', rpc_method_handlers)

    server.add_generic_rpc_handlers((generic_handler,))





 # This class is part of an EXPERIMENTAL API.

class GrpcKafkaUpdatesProcessor(object):

    """Missing associated documentation comment in .proto file."""



    @staticmethod

    def StartUpdatesStream(request_iterator,

            target,

            options=(),

            channel_credentials=None,

            call_credentials=None,

            insecure=False,

            compression=None,

            wait_for_ready=None,

            timeout=None,

            metadata=None):

        return grpc.experimental.stream_unary(request_iterator, target, '/ficus.GrpcKafkaUpdatesProcessor/StartUpdatesStream',

            kafka__service__pb2.GrpcKafkaUpdate.SerializeToString,

            google_dot_protobuf_dot_empty__pb2.Empty.FromString,

            options, channel_credentials,

            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
