# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!

"""Client and server classes corresponding to protobuf-defined services."""

import grpc



import ficus.grpc_pipelines.models.backend_service_pb2 as backend__service__pb2

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

import ficus.grpc_pipelines.models.kafka_service_pb2 as kafka__service__pb2





class GrpcKafkaServiceStub(object):

    """Missing associated documentation comment in .proto file."""



    def __init__(self, channel):

        """Constructor.



        Args:

            channel: A grpc.Channel.

        """

        self.SubscribeForKafkaTopic = channel.unary_unary(

                '/ficus.GrpcKafkaService/SubscribeForKafkaTopic',

                request_serializer=kafka__service__pb2.GrpcSubscribeToKafkaRequest.SerializeToString,

                response_deserializer=kafka__service__pb2.GrpcKafkaResult.FromString,

                )

        self.UnsubscribeFromKafkaTopic = channel.unary_unary(

                '/ficus.GrpcKafkaService/UnsubscribeFromKafkaTopic',

                request_serializer=kafka__service__pb2.GrpcUnsubscribeFromKafkaRequest.SerializeToString,

                response_deserializer=kafka__service__pb2.GrpcKafkaResult.FromString,

                )

        self.AddPipelineToSubscription = channel.unary_unary(

                '/ficus.GrpcKafkaService/AddPipelineToSubscription',

                request_serializer=kafka__service__pb2.GrpcAddPipelineRequest.SerializeToString,

                response_deserializer=kafka__service__pb2.GrpcKafkaResult.FromString,

                )

        self.AddPipelineToSubscriptionStream = channel.unary_stream(

                '/ficus.GrpcKafkaService/AddPipelineToSubscriptionStream',

                request_serializer=kafka__service__pb2.GrpcAddPipelineStreamRequest.SerializeToString,

                response_deserializer=backend__service__pb2.GrpcPipelinePartExecutionResult.FromString,

                )

        self.RemovePipelineSubscription = channel.unary_unary(

                '/ficus.GrpcKafkaService/RemovePipelineSubscription',

                request_serializer=kafka__service__pb2.GrpcRemovePipelineRequest.SerializeToString,

                response_deserializer=kafka__service__pb2.GrpcKafkaResult.FromString,

                )

        self.RemoveAllPipelineSubscriptions = channel.unary_unary(

                '/ficus.GrpcKafkaService/RemoveAllPipelineSubscriptions',

                request_serializer=kafka__service__pb2.GrpcRemoveAllPipelinesRequest.SerializeToString,

                response_deserializer=kafka__service__pb2.GrpcKafkaResult.FromString,

                )

        self.GetAllSubscriptionsAndPipelines = channel.unary_unary(

                '/ficus.GrpcKafkaService/GetAllSubscriptionsAndPipelines',

                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,

                response_deserializer=kafka__service__pb2.GrpcGetAllSubscriptionsAndPipelinesResponse.FromString,

                )

        self.ExecutePipelineAndProduceToKafka = channel.unary_stream(

                '/ficus.GrpcKafkaService/ExecutePipelineAndProduceToKafka',

                request_serializer=kafka__service__pb2.GrpcExecutePipelineAndProduceKafkaRequest.SerializeToString,

                response_deserializer=backend__service__pb2.GrpcPipelinePartExecutionResult.FromString,

                )





class GrpcKafkaServiceServicer(object):

    """Missing associated documentation comment in .proto file."""



    def SubscribeForKafkaTopic(self, request, context):

        """Missing associated documentation comment in .proto file."""

        context.set_code(grpc.StatusCode.UNIMPLEMENTED)

        context.set_details('Method not implemented!')

        raise NotImplementedError('Method not implemented!')



    def UnsubscribeFromKafkaTopic(self, request, context):

        """Missing associated documentation comment in .proto file."""

        context.set_code(grpc.StatusCode.UNIMPLEMENTED)

        context.set_details('Method not implemented!')

        raise NotImplementedError('Method not implemented!')



    def AddPipelineToSubscription(self, request, context):

        """Missing associated documentation comment in .proto file."""

        context.set_code(grpc.StatusCode.UNIMPLEMENTED)

        context.set_details('Method not implemented!')

        raise NotImplementedError('Method not implemented!')



    def AddPipelineToSubscriptionStream(self, request, context):

        """Missing associated documentation comment in .proto file."""

        context.set_code(grpc.StatusCode.UNIMPLEMENTED)

        context.set_details('Method not implemented!')

        raise NotImplementedError('Method not implemented!')



    def RemovePipelineSubscription(self, request, context):

        """Missing associated documentation comment in .proto file."""

        context.set_code(grpc.StatusCode.UNIMPLEMENTED)

        context.set_details('Method not implemented!')

        raise NotImplementedError('Method not implemented!')



    def RemoveAllPipelineSubscriptions(self, request, context):

        """Missing associated documentation comment in .proto file."""

        context.set_code(grpc.StatusCode.UNIMPLEMENTED)

        context.set_details('Method not implemented!')

        raise NotImplementedError('Method not implemented!')



    def GetAllSubscriptionsAndPipelines(self, request, context):

        """Missing associated documentation comment in .proto file."""

        context.set_code(grpc.StatusCode.UNIMPLEMENTED)

        context.set_details('Method not implemented!')

        raise NotImplementedError('Method not implemented!')



    def ExecutePipelineAndProduceToKafka(self, request, context):

        """Missing associated documentation comment in .proto file."""

        context.set_code(grpc.StatusCode.UNIMPLEMENTED)

        context.set_details('Method not implemented!')

        raise NotImplementedError('Method not implemented!')





def add_GrpcKafkaServiceServicer_to_server(servicer, server):

    rpc_method_handlers = {

            'SubscribeForKafkaTopic': grpc.unary_unary_rpc_method_handler(

                    servicer.SubscribeForKafkaTopic,

                    request_deserializer=kafka__service__pb2.GrpcSubscribeToKafkaRequest.FromString,

                    response_serializer=kafka__service__pb2.GrpcKafkaResult.SerializeToString,

            ),

            'UnsubscribeFromKafkaTopic': grpc.unary_unary_rpc_method_handler(

                    servicer.UnsubscribeFromKafkaTopic,

                    request_deserializer=kafka__service__pb2.GrpcUnsubscribeFromKafkaRequest.FromString,

                    response_serializer=kafka__service__pb2.GrpcKafkaResult.SerializeToString,

            ),

            'AddPipelineToSubscription': grpc.unary_unary_rpc_method_handler(

                    servicer.AddPipelineToSubscription,

                    request_deserializer=kafka__service__pb2.GrpcAddPipelineRequest.FromString,

                    response_serializer=kafka__service__pb2.GrpcKafkaResult.SerializeToString,

            ),

            'AddPipelineToSubscriptionStream': grpc.unary_stream_rpc_method_handler(

                    servicer.AddPipelineToSubscriptionStream,

                    request_deserializer=kafka__service__pb2.GrpcAddPipelineStreamRequest.FromString,

                    response_serializer=backend__service__pb2.GrpcPipelinePartExecutionResult.SerializeToString,

            ),

            'RemovePipelineSubscription': grpc.unary_unary_rpc_method_handler(

                    servicer.RemovePipelineSubscription,

                    request_deserializer=kafka__service__pb2.GrpcRemovePipelineRequest.FromString,

                    response_serializer=kafka__service__pb2.GrpcKafkaResult.SerializeToString,

            ),

            'RemoveAllPipelineSubscriptions': grpc.unary_unary_rpc_method_handler(

                    servicer.RemoveAllPipelineSubscriptions,

                    request_deserializer=kafka__service__pb2.GrpcRemoveAllPipelinesRequest.FromString,

                    response_serializer=kafka__service__pb2.GrpcKafkaResult.SerializeToString,

            ),

            'GetAllSubscriptionsAndPipelines': grpc.unary_unary_rpc_method_handler(

                    servicer.GetAllSubscriptionsAndPipelines,

                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,

                    response_serializer=kafka__service__pb2.GrpcGetAllSubscriptionsAndPipelinesResponse.SerializeToString,

            ),

            'ExecutePipelineAndProduceToKafka': grpc.unary_stream_rpc_method_handler(

                    servicer.ExecutePipelineAndProduceToKafka,

                    request_deserializer=kafka__service__pb2.GrpcExecutePipelineAndProduceKafkaRequest.FromString,

                    response_serializer=backend__service__pb2.GrpcPipelinePartExecutionResult.SerializeToString,

            ),

    }

    generic_handler = grpc.method_handlers_generic_handler(

            'ficus.GrpcKafkaService', rpc_method_handlers)

    server.add_generic_rpc_handlers((generic_handler,))





 # This class is part of an EXPERIMENTAL API.

class GrpcKafkaService(object):

    """Missing associated documentation comment in .proto file."""



    @staticmethod

    def SubscribeForKafkaTopic(request,

            target,

            options=(),

            channel_credentials=None,

            call_credentials=None,

            insecure=False,

            compression=None,

            wait_for_ready=None,

            timeout=None,

            metadata=None):

        return grpc.experimental.unary_unary(request, target, '/ficus.GrpcKafkaService/SubscribeForKafkaTopic',

            kafka__service__pb2.GrpcSubscribeToKafkaRequest.SerializeToString,

            kafka__service__pb2.GrpcKafkaResult.FromString,

            options, channel_credentials,

            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)



    @staticmethod

    def UnsubscribeFromKafkaTopic(request,

            target,

            options=(),

            channel_credentials=None,

            call_credentials=None,

            insecure=False,

            compression=None,

            wait_for_ready=None,

            timeout=None,

            metadata=None):

        return grpc.experimental.unary_unary(request, target, '/ficus.GrpcKafkaService/UnsubscribeFromKafkaTopic',

            kafka__service__pb2.GrpcUnsubscribeFromKafkaRequest.SerializeToString,

            kafka__service__pb2.GrpcKafkaResult.FromString,

            options, channel_credentials,

            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)



    @staticmethod

    def AddPipelineToSubscription(request,

            target,

            options=(),

            channel_credentials=None,

            call_credentials=None,

            insecure=False,

            compression=None,

            wait_for_ready=None,

            timeout=None,

            metadata=None):

        return grpc.experimental.unary_unary(request, target, '/ficus.GrpcKafkaService/AddPipelineToSubscription',

            kafka__service__pb2.GrpcAddPipelineRequest.SerializeToString,

            kafka__service__pb2.GrpcKafkaResult.FromString,

            options, channel_credentials,

            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)



    @staticmethod

    def AddPipelineToSubscriptionStream(request,

            target,

            options=(),

            channel_credentials=None,

            call_credentials=None,

            insecure=False,

            compression=None,

            wait_for_ready=None,

            timeout=None,

            metadata=None):

        return grpc.experimental.unary_stream(request, target, '/ficus.GrpcKafkaService/AddPipelineToSubscriptionStream',

            kafka__service__pb2.GrpcAddPipelineStreamRequest.SerializeToString,

            backend__service__pb2.GrpcPipelinePartExecutionResult.FromString,

            options, channel_credentials,

            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)



    @staticmethod

    def RemovePipelineSubscription(request,

            target,

            options=(),

            channel_credentials=None,

            call_credentials=None,

            insecure=False,

            compression=None,

            wait_for_ready=None,

            timeout=None,

            metadata=None):

        return grpc.experimental.unary_unary(request, target, '/ficus.GrpcKafkaService/RemovePipelineSubscription',

            kafka__service__pb2.GrpcRemovePipelineRequest.SerializeToString,

            kafka__service__pb2.GrpcKafkaResult.FromString,

            options, channel_credentials,

            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)



    @staticmethod

    def RemoveAllPipelineSubscriptions(request,

            target,

            options=(),

            channel_credentials=None,

            call_credentials=None,

            insecure=False,

            compression=None,

            wait_for_ready=None,

            timeout=None,

            metadata=None):

        return grpc.experimental.unary_unary(request, target, '/ficus.GrpcKafkaService/RemoveAllPipelineSubscriptions',

            kafka__service__pb2.GrpcRemoveAllPipelinesRequest.SerializeToString,

            kafka__service__pb2.GrpcKafkaResult.FromString,

            options, channel_credentials,

            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)



    @staticmethod

    def GetAllSubscriptionsAndPipelines(request,

            target,

            options=(),

            channel_credentials=None,

            call_credentials=None,

            insecure=False,

            compression=None,

            wait_for_ready=None,

            timeout=None,

            metadata=None):

        return grpc.experimental.unary_unary(request, target, '/ficus.GrpcKafkaService/GetAllSubscriptionsAndPipelines',

            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,

            kafka__service__pb2.GrpcGetAllSubscriptionsAndPipelinesResponse.FromString,

            options, channel_credentials,

            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)



    @staticmethod

    def ExecutePipelineAndProduceToKafka(request,

            target,

            options=(),

            channel_credentials=None,

            call_credentials=None,

            insecure=False,

            compression=None,

            wait_for_ready=None,

            timeout=None,

            metadata=None):

        return grpc.experimental.unary_stream(request, target, '/ficus.GrpcKafkaService/ExecutePipelineAndProduceToKafka',

            kafka__service__pb2.GrpcExecutePipelineAndProduceKafkaRequest.SerializeToString,

            backend__service__pb2.GrpcPipelinePartExecutionResult.FromString,

            options, channel_credentials,

            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
