// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.28.3
// source: backend_service.proto

package grpc_models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrpcFicusBackendInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PipelineParts []*GrpcPipelinePartDescriptor `protobuf:"bytes,2,rep,name=pipeline_parts,json=pipelineParts,proto3" json:"pipeline_parts,omitempty"`
}

func (x *GrpcFicusBackendInfo) Reset() {
	*x = GrpcFicusBackendInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcFicusBackendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcFicusBackendInfo) ProtoMessage() {}

func (x *GrpcFicusBackendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcFicusBackendInfo.ProtoReflect.Descriptor instead.
func (*GrpcFicusBackendInfo) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{0}
}

func (x *GrpcFicusBackendInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GrpcFicusBackendInfo) GetPipelineParts() []*GrpcPipelinePartDescriptor {
	if x != nil {
		return x.PipelineParts
	}
	return nil
}

type GrpcPipelinePartDescriptor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GrpcPipelinePartDescriptor) Reset() {
	*x = GrpcPipelinePartDescriptor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcPipelinePartDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPipelinePartDescriptor) ProtoMessage() {}

func (x *GrpcPipelinePartDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPipelinePartDescriptor.ProtoReflect.Descriptor instead.
func (*GrpcPipelinePartDescriptor) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{1}
}

func (x *GrpcPipelinePartDescriptor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GrpcGetContextValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExecutionId *GrpcGuid       `protobuf:"bytes,2,opt,name=executionId,proto3" json:"executionId,omitempty"`
	Key         *GrpcContextKey `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GrpcGetContextValueRequest) Reset() {
	*x = GrpcGetContextValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcGetContextValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcGetContextValueRequest) ProtoMessage() {}

func (x *GrpcGetContextValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcGetContextValueRequest.ProtoReflect.Descriptor instead.
func (*GrpcGetContextValueRequest) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{2}
}

func (x *GrpcGetContextValueRequest) GetExecutionId() *GrpcGuid {
	if x != nil {
		return x.ExecutionId
	}
	return nil
}

func (x *GrpcGetContextValueRequest) GetKey() *GrpcContextKey {
	if x != nil {
		return x.Key
	}
	return nil
}

type GrpcPipelineExecutionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pipeline       *GrpcPipeline          `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	InitialContext []*GrpcContextKeyValue `protobuf:"bytes,2,rep,name=initialContext,proto3" json:"initialContext,omitempty"`
}

func (x *GrpcPipelineExecutionRequest) Reset() {
	*x = GrpcPipelineExecutionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcPipelineExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPipelineExecutionRequest) ProtoMessage() {}

func (x *GrpcPipelineExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPipelineExecutionRequest.ProtoReflect.Descriptor instead.
func (*GrpcPipelineExecutionRequest) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{3}
}

func (x *GrpcPipelineExecutionRequest) GetPipeline() *GrpcPipeline {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

func (x *GrpcPipelineExecutionRequest) GetInitialContext() []*GrpcContextKeyValue {
	if x != nil {
		return x.InitialContext
	}
	return nil
}

type GrpcProxyPipelineExecutionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pipeline         *GrpcPipeline `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	ContextValuesIds []*GrpcGuid   `protobuf:"bytes,2,rep,name=contextValuesIds,proto3" json:"contextValuesIds,omitempty"`
}

func (x *GrpcProxyPipelineExecutionRequest) Reset() {
	*x = GrpcProxyPipelineExecutionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcProxyPipelineExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcProxyPipelineExecutionRequest) ProtoMessage() {}

func (x *GrpcProxyPipelineExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcProxyPipelineExecutionRequest.ProtoReflect.Descriptor instead.
func (*GrpcProxyPipelineExecutionRequest) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{4}
}

func (x *GrpcProxyPipelineExecutionRequest) GetPipeline() *GrpcPipeline {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

func (x *GrpcProxyPipelineExecutionRequest) GetContextValuesIds() []*GrpcGuid {
	if x != nil {
		return x.ContextValuesIds
	}
	return nil
}

type GrpcPipelinePartExecutionResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*GrpcPipelinePartExecutionResult_FinalResult
	//	*GrpcPipelinePartExecutionResult_PipelinePartResult
	//	*GrpcPipelinePartExecutionResult_LogMessage
	Result isGrpcPipelinePartExecutionResult_Result `protobuf_oneof:"result"`
}

func (x *GrpcPipelinePartExecutionResult) Reset() {
	*x = GrpcPipelinePartExecutionResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcPipelinePartExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPipelinePartExecutionResult) ProtoMessage() {}

func (x *GrpcPipelinePartExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPipelinePartExecutionResult.ProtoReflect.Descriptor instead.
func (*GrpcPipelinePartExecutionResult) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{5}
}

func (m *GrpcPipelinePartExecutionResult) GetResult() isGrpcPipelinePartExecutionResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *GrpcPipelinePartExecutionResult) GetFinalResult() *GrpcPipelineFinalResult {
	if x, ok := x.GetResult().(*GrpcPipelinePartExecutionResult_FinalResult); ok {
		return x.FinalResult
	}
	return nil
}

func (x *GrpcPipelinePartExecutionResult) GetPipelinePartResult() *GrpcPipelinePartResult {
	if x, ok := x.GetResult().(*GrpcPipelinePartExecutionResult_PipelinePartResult); ok {
		return x.PipelinePartResult
	}
	return nil
}

func (x *GrpcPipelinePartExecutionResult) GetLogMessage() *GrpcPipelinePartLogMessage {
	if x, ok := x.GetResult().(*GrpcPipelinePartExecutionResult_LogMessage); ok {
		return x.LogMessage
	}
	return nil
}

type isGrpcPipelinePartExecutionResult_Result interface {
	isGrpcPipelinePartExecutionResult_Result()
}

type GrpcPipelinePartExecutionResult_FinalResult struct {
	FinalResult *GrpcPipelineFinalResult `protobuf:"bytes,1,opt,name=finalResult,proto3,oneof"`
}

type GrpcPipelinePartExecutionResult_PipelinePartResult struct {
	PipelinePartResult *GrpcPipelinePartResult `protobuf:"bytes,2,opt,name=pipelinePartResult,proto3,oneof"`
}

type GrpcPipelinePartExecutionResult_LogMessage struct {
	LogMessage *GrpcPipelinePartLogMessage `protobuf:"bytes,3,opt,name=logMessage,proto3,oneof"`
}

func (*GrpcPipelinePartExecutionResult_FinalResult) isGrpcPipelinePartExecutionResult_Result() {}

func (*GrpcPipelinePartExecutionResult_PipelinePartResult) isGrpcPipelinePartExecutionResult_Result() {
}

func (*GrpcPipelinePartExecutionResult_LogMessage) isGrpcPipelinePartExecutionResult_Result() {}

type GrpcPipelinePartLogMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GrpcPipelinePartLogMessage) Reset() {
	*x = GrpcPipelinePartLogMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcPipelinePartLogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPipelinePartLogMessage) ProtoMessage() {}

func (x *GrpcPipelinePartLogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPipelinePartLogMessage.ProtoReflect.Descriptor instead.
func (*GrpcPipelinePartLogMessage) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{6}
}

func (x *GrpcPipelinePartLogMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GrpcPipelinePartResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContextValues []*GrpcContextValueWithKeyName `protobuf:"bytes,1,rep,name=contextValues,proto3" json:"contextValues,omitempty"`
	Uuid          *GrpcUuid                      `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *GrpcPipelinePartResult) Reset() {
	*x = GrpcPipelinePartResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcPipelinePartResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPipelinePartResult) ProtoMessage() {}

func (x *GrpcPipelinePartResult) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPipelinePartResult.ProtoReflect.Descriptor instead.
func (*GrpcPipelinePartResult) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{7}
}

func (x *GrpcPipelinePartResult) GetContextValues() []*GrpcContextValueWithKeyName {
	if x != nil {
		return x.ContextValues
	}
	return nil
}

func (x *GrpcPipelinePartResult) GetUuid() *GrpcUuid {
	if x != nil {
		return x.Uuid
	}
	return nil
}

type GrpcPipelineFinalResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to ExecutionResult:
	//
	//	*GrpcPipelineFinalResult_Success
	//	*GrpcPipelineFinalResult_Error
	ExecutionResult isGrpcPipelineFinalResult_ExecutionResult `protobuf_oneof:"executionResult"`
}

func (x *GrpcPipelineFinalResult) Reset() {
	*x = GrpcPipelineFinalResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcPipelineFinalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPipelineFinalResult) ProtoMessage() {}

func (x *GrpcPipelineFinalResult) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPipelineFinalResult.ProtoReflect.Descriptor instead.
func (*GrpcPipelineFinalResult) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{8}
}

func (m *GrpcPipelineFinalResult) GetExecutionResult() isGrpcPipelineFinalResult_ExecutionResult {
	if m != nil {
		return m.ExecutionResult
	}
	return nil
}

func (x *GrpcPipelineFinalResult) GetSuccess() *GrpcGuid {
	if x, ok := x.GetExecutionResult().(*GrpcPipelineFinalResult_Success); ok {
		return x.Success
	}
	return nil
}

func (x *GrpcPipelineFinalResult) GetError() string {
	if x, ok := x.GetExecutionResult().(*GrpcPipelineFinalResult_Error); ok {
		return x.Error
	}
	return ""
}

type isGrpcPipelineFinalResult_ExecutionResult interface {
	isGrpcPipelineFinalResult_ExecutionResult()
}

type GrpcPipelineFinalResult_Success struct {
	Success *GrpcGuid `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type GrpcPipelineFinalResult_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GrpcPipelineFinalResult_Success) isGrpcPipelineFinalResult_ExecutionResult() {}

func (*GrpcPipelineFinalResult_Error) isGrpcPipelineFinalResult_ExecutionResult() {}

type GrpcGetContextValueResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to ContextValueResult:
	//
	//	*GrpcGetContextValueResult_Value
	//	*GrpcGetContextValueResult_Error
	ContextValueResult isGrpcGetContextValueResult_ContextValueResult `protobuf_oneof:"contextValueResult"`
}

func (x *GrpcGetContextValueResult) Reset() {
	*x = GrpcGetContextValueResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcGetContextValueResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcGetContextValueResult) ProtoMessage() {}

func (x *GrpcGetContextValueResult) ProtoReflect() protoreflect.Message {
	mi := &file_backend_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcGetContextValueResult.ProtoReflect.Descriptor instead.
func (*GrpcGetContextValueResult) Descriptor() ([]byte, []int) {
	return file_backend_service_proto_rawDescGZIP(), []int{9}
}

func (m *GrpcGetContextValueResult) GetContextValueResult() isGrpcGetContextValueResult_ContextValueResult {
	if m != nil {
		return m.ContextValueResult
	}
	return nil
}

func (x *GrpcGetContextValueResult) GetValue() *GrpcContextValue {
	if x, ok := x.GetContextValueResult().(*GrpcGetContextValueResult_Value); ok {
		return x.Value
	}
	return nil
}

func (x *GrpcGetContextValueResult) GetError() string {
	if x, ok := x.GetContextValueResult().(*GrpcGetContextValueResult_Error); ok {
		return x.Error
	}
	return ""
}

type isGrpcGetContextValueResult_ContextValueResult interface {
	isGrpcGetContextValueResult_ContextValueResult()
}

type GrpcGetContextValueResult_Value struct {
	Value *GrpcContextValue `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

type GrpcGetContextValueResult_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GrpcGetContextValueResult_Value) isGrpcGetContextValueResult_ContextValueResult() {}

func (*GrpcGetContextValueResult_Error) isGrpcGetContextValueResult_ContextValueResult() {}

var File_backend_service_proto protoreflect.FileDescriptor

var file_backend_service_proto_rawDesc = []byte{
	0x0a, 0x15, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x66, 0x69, 0x63, 0x75, 0x73, 0x1a, 0x1b,
	0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x5f, 0x61, 0x6e, 0x64, 0x5f, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x75, 0x74, 0x69,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x74, 0x0a, 0x14, 0x47, 0x72, 0x70, 0x63, 0x46, 0x69, 0x63, 0x75,
	0x73, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x48, 0x0a, 0x0e, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x70, 0x61, 0x72,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73,
	0x2e, 0x47, 0x72, 0x70, 0x63, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x61, 0x72,
	0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x52, 0x0d, 0x70, 0x69, 0x70,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x61, 0x72, 0x74, 0x73, 0x22, 0x30, 0x0a, 0x1a, 0x47, 0x72,
	0x70, 0x63, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x61, 0x72, 0x74, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x78, 0x0a, 0x1a,
	0x47, 0x72, 0x70, 0x63, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x0b, 0x65, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x47, 0x75, 0x69, 0x64,
	0x52, 0x0b, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x27, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x66, 0x69, 0x63,
	0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x4b, 0x65,
	0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x93, 0x01, 0x0a, 0x1c, 0x47, 0x72, 0x70, 0x63, 0x50,
	0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x08, 0x70, 0x69, 0x70, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x66, 0x69, 0x63, 0x75,
	0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x08,
	0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x42, 0x0a, 0x0e, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0e, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x61, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x91, 0x01, 0x0a,
	0x21, 0x47, 0x72, 0x70, 0x63, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2f, 0x0a, 0x08, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70,
	0x63, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x08, 0x70, 0x69, 0x70, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x12, 0x3b, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x47, 0x75, 0x69, 0x64, 0x52, 0x10,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x49, 0x64, 0x73,
	0x22, 0x85, 0x02, 0x0a, 0x1f, 0x47, 0x72, 0x70, 0x63, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x50, 0x61, 0x72, 0x74, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x42, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x66, 0x69, 0x63, 0x75,
	0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x46, 0x69,
	0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x66, 0x69, 0x6e,
	0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x4f, 0x0a, 0x12, 0x70, 0x69, 0x70, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70,
	0x63, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x12, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x50,
	0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x43, 0x0a, 0x0a, 0x6c, 0x6f, 0x67,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x50, 0x61, 0x72, 0x74, 0x4c, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x48, 0x00, 0x52, 0x0a, 0x6c, 0x6f, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x08,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x36, 0x0a, 0x1a, 0x47, 0x72, 0x70, 0x63,
	0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x61, 0x72, 0x74, 0x4c, 0x6f, 0x67, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x87, 0x01, 0x0a, 0x16, 0x47, 0x72, 0x70, 0x63, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x50, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x48, 0x0a, 0x0d, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x57, 0x69, 0x74, 0x68, 0x4b,
	0x65, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63,
	0x55, 0x75, 0x69, 0x64, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x71, 0x0a, 0x17, 0x47, 0x72,
	0x70, 0x63, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2b, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47,
	0x72, 0x70, 0x63, 0x47, 0x75, 0x69, 0x64, 0x48, 0x00, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x11, 0x0a, 0x0f, 0x65, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x7a, 0x0a,
	0x19, 0x47, 0x72, 0x70, 0x63, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2f, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x66, 0x69, 0x63, 0x75,
	0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x42, 0x14, 0x0a, 0x12, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xda, 0x02, 0x0a, 0x12, 0x47, 0x72,
	0x70, 0x63, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x65, 0x0a, 0x0f, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x69, 0x70, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x12, 0x28, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63,
	0x50, 0x72, 0x6f, 0x78, 0x79, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e,
	0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x50, 0x61, 0x72, 0x74, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x30, 0x01, 0x12, 0x56, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x21, 0x2e, 0x66, 0x69, 0x63,
	0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x3e, 0x0a, 0x13, 0x44, 0x72, 0x6f, 0x70, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0f, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47,
	0x72, 0x70, 0x63, 0x47, 0x75, 0x69, 0x64, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x45, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1b, 0x2e, 0x66, 0x69, 0x63, 0x75,
	0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x46, 0x69, 0x63, 0x75, 0x73, 0x42, 0x61, 0x63, 0x6b, 0x65,
	0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x0d, 0x5a, 0x0b, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_backend_service_proto_rawDescOnce sync.Once
	file_backend_service_proto_rawDescData = file_backend_service_proto_rawDesc
)

func file_backend_service_proto_rawDescGZIP() []byte {
	file_backend_service_proto_rawDescOnce.Do(func() {
		file_backend_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_backend_service_proto_rawDescData)
	})
	return file_backend_service_proto_rawDescData
}

var file_backend_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_backend_service_proto_goTypes = []interface{}{
	(*GrpcFicusBackendInfo)(nil),              // 0: ficus.GrpcFicusBackendInfo
	(*GrpcPipelinePartDescriptor)(nil),        // 1: ficus.GrpcPipelinePartDescriptor
	(*GrpcGetContextValueRequest)(nil),        // 2: ficus.GrpcGetContextValueRequest
	(*GrpcPipelineExecutionRequest)(nil),      // 3: ficus.GrpcPipelineExecutionRequest
	(*GrpcProxyPipelineExecutionRequest)(nil), // 4: ficus.GrpcProxyPipelineExecutionRequest
	(*GrpcPipelinePartExecutionResult)(nil),   // 5: ficus.GrpcPipelinePartExecutionResult
	(*GrpcPipelinePartLogMessage)(nil),        // 6: ficus.GrpcPipelinePartLogMessage
	(*GrpcPipelinePartResult)(nil),            // 7: ficus.GrpcPipelinePartResult
	(*GrpcPipelineFinalResult)(nil),           // 8: ficus.GrpcPipelineFinalResult
	(*GrpcGetContextValueResult)(nil),         // 9: ficus.GrpcGetContextValueResult
	(*GrpcGuid)(nil),                          // 10: ficus.GrpcGuid
	(*GrpcContextKey)(nil),                    // 11: ficus.GrpcContextKey
	(*GrpcPipeline)(nil),                      // 12: ficus.GrpcPipeline
	(*GrpcContextKeyValue)(nil),               // 13: ficus.GrpcContextKeyValue
	(*GrpcContextValueWithKeyName)(nil),       // 14: ficus.GrpcContextValueWithKeyName
	(*GrpcUuid)(nil),                          // 15: ficus.GrpcUuid
	(*GrpcContextValue)(nil),                  // 16: ficus.GrpcContextValue
	(*emptypb.Empty)(nil),                     // 17: google.protobuf.Empty
}
var file_backend_service_proto_depIdxs = []int32{
	1,  // 0: ficus.GrpcFicusBackendInfo.pipeline_parts:type_name -> ficus.GrpcPipelinePartDescriptor
	10, // 1: ficus.GrpcGetContextValueRequest.executionId:type_name -> ficus.GrpcGuid
	11, // 2: ficus.GrpcGetContextValueRequest.key:type_name -> ficus.GrpcContextKey
	12, // 3: ficus.GrpcPipelineExecutionRequest.pipeline:type_name -> ficus.GrpcPipeline
	13, // 4: ficus.GrpcPipelineExecutionRequest.initialContext:type_name -> ficus.GrpcContextKeyValue
	12, // 5: ficus.GrpcProxyPipelineExecutionRequest.pipeline:type_name -> ficus.GrpcPipeline
	10, // 6: ficus.GrpcProxyPipelineExecutionRequest.contextValuesIds:type_name -> ficus.GrpcGuid
	8,  // 7: ficus.GrpcPipelinePartExecutionResult.finalResult:type_name -> ficus.GrpcPipelineFinalResult
	7,  // 8: ficus.GrpcPipelinePartExecutionResult.pipelinePartResult:type_name -> ficus.GrpcPipelinePartResult
	6,  // 9: ficus.GrpcPipelinePartExecutionResult.logMessage:type_name -> ficus.GrpcPipelinePartLogMessage
	14, // 10: ficus.GrpcPipelinePartResult.contextValues:type_name -> ficus.GrpcContextValueWithKeyName
	15, // 11: ficus.GrpcPipelinePartResult.uuid:type_name -> ficus.GrpcUuid
	10, // 12: ficus.GrpcPipelineFinalResult.success:type_name -> ficus.GrpcGuid
	16, // 13: ficus.GrpcGetContextValueResult.value:type_name -> ficus.GrpcContextValue
	4,  // 14: ficus.GrpcBackendService.ExecutePipeline:input_type -> ficus.GrpcProxyPipelineExecutionRequest
	2,  // 15: ficus.GrpcBackendService.GetContextValue:input_type -> ficus.GrpcGetContextValueRequest
	10, // 16: ficus.GrpcBackendService.DropExecutionResult:input_type -> ficus.GrpcGuid
	17, // 17: ficus.GrpcBackendService.GetBackendInfo:input_type -> google.protobuf.Empty
	5,  // 18: ficus.GrpcBackendService.ExecutePipeline:output_type -> ficus.GrpcPipelinePartExecutionResult
	9,  // 19: ficus.GrpcBackendService.GetContextValue:output_type -> ficus.GrpcGetContextValueResult
	17, // 20: ficus.GrpcBackendService.DropExecutionResult:output_type -> google.protobuf.Empty
	0,  // 21: ficus.GrpcBackendService.GetBackendInfo:output_type -> ficus.GrpcFicusBackendInfo
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_backend_service_proto_init() }
func file_backend_service_proto_init() {
	if File_backend_service_proto != nil {
		return
	}
	file_pipelines_and_context_proto_init()
	file_util_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_backend_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcFicusBackendInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcPipelinePartDescriptor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcGetContextValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcPipelineExecutionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcProxyPipelineExecutionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcPipelinePartExecutionResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcPipelinePartLogMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcPipelinePartResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcPipelineFinalResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcGetContextValueResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_backend_service_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*GrpcPipelinePartExecutionResult_FinalResult)(nil),
		(*GrpcPipelinePartExecutionResult_PipelinePartResult)(nil),
		(*GrpcPipelinePartExecutionResult_LogMessage)(nil),
	}
	file_backend_service_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*GrpcPipelineFinalResult_Success)(nil),
		(*GrpcPipelineFinalResult_Error)(nil),
	}
	file_backend_service_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*GrpcGetContextValueResult_Value)(nil),
		(*GrpcGetContextValueResult_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_backend_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_service_proto_goTypes,
		DependencyIndexes: file_backend_service_proto_depIdxs,
		MessageInfos:      file_backend_service_proto_msgTypes,
	}.Build()
	File_backend_service_proto = out.File
	file_backend_service_proto_rawDesc = nil
	file_backend_service_proto_goTypes = nil
	file_backend_service_proto_depIdxs = nil
}
