// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.28.3
// source: context_values_service.proto

package grpc_models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrpcContextValuePart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Bytes []byte `protobuf:"bytes,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
}

func (x *GrpcContextValuePart) Reset() {
	*x = GrpcContextValuePart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_context_values_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcContextValuePart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcContextValuePart) ProtoMessage() {}

func (x *GrpcContextValuePart) ProtoReflect() protoreflect.Message {
	mi := &file_context_values_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcContextValuePart.ProtoReflect.Descriptor instead.
func (*GrpcContextValuePart) Descriptor() ([]byte, []int) {
	return file_context_values_service_proto_rawDescGZIP(), []int{0}
}

func (x *GrpcContextValuePart) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GrpcContextValuePart) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type GrpcDropContextValuesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []*GrpcGuid `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GrpcDropContextValuesRequest) Reset() {
	*x = GrpcDropContextValuesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_context_values_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcDropContextValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcDropContextValuesRequest) ProtoMessage() {}

func (x *GrpcDropContextValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_context_values_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcDropContextValuesRequest.ProtoReflect.Descriptor instead.
func (*GrpcDropContextValuesRequest) Descriptor() ([]byte, []int) {
	return file_context_values_service_proto_rawDescGZIP(), []int{1}
}

func (x *GrpcDropContextValuesRequest) GetIds() []*GrpcGuid {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_context_values_service_proto protoreflect.FileDescriptor

var file_context_values_service_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x66, 0x69, 0x63, 0x75, 0x73, 0x1a, 0x1b, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x73,
	0x5f, 0x61, 0x6e, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x0a, 0x75, 0x74, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x14, 0x47,
	0x72, 0x70, 0x63, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50,
	0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x22, 0x41, 0x0a, 0x1c, 0x47,
	0x72, 0x70, 0x63, 0x44, 0x72, 0x6f, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x03, 0x69,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73,
	0x2e, 0x47, 0x72, 0x70, 0x63, 0x47, 0x75, 0x69, 0x64, 0x52, 0x03, 0x69, 0x64, 0x73, 0x32, 0xaf,
	0x01, 0x0a, 0x18, 0x47, 0x72, 0x70, 0x63, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0f, 0x53,
	0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b,
	0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x72, 0x74, 0x1a, 0x0f, 0x2e, 0x66, 0x69,
	0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x47, 0x75, 0x69, 0x64, 0x28, 0x01, 0x12, 0x50,
	0x0a, 0x11, 0x44, 0x72, 0x6f, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x12, 0x23, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63,
	0x44, 0x72, 0x6f, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x42, 0x0d, 0x5a, 0x0b, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_context_values_service_proto_rawDescOnce sync.Once
	file_context_values_service_proto_rawDescData = file_context_values_service_proto_rawDesc
)

func file_context_values_service_proto_rawDescGZIP() []byte {
	file_context_values_service_proto_rawDescOnce.Do(func() {
		file_context_values_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_context_values_service_proto_rawDescData)
	})
	return file_context_values_service_proto_rawDescData
}

var file_context_values_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_context_values_service_proto_goTypes = []interface{}{
	(*GrpcContextValuePart)(nil),         // 0: ficus.GrpcContextValuePart
	(*GrpcDropContextValuesRequest)(nil), // 1: ficus.GrpcDropContextValuesRequest
	(*GrpcGuid)(nil),                     // 2: ficus.GrpcGuid
	(*emptypb.Empty)(nil),                // 3: google.protobuf.Empty
}
var file_context_values_service_proto_depIdxs = []int32{
	2, // 0: ficus.GrpcDropContextValuesRequest.ids:type_name -> ficus.GrpcGuid
	0, // 1: ficus.GrpcContextValuesService.SetContextValue:input_type -> ficus.GrpcContextValuePart
	1, // 2: ficus.GrpcContextValuesService.DropContextValues:input_type -> ficus.GrpcDropContextValuesRequest
	2, // 3: ficus.GrpcContextValuesService.SetContextValue:output_type -> ficus.GrpcGuid
	3, // 4: ficus.GrpcContextValuesService.DropContextValues:output_type -> google.protobuf.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_context_values_service_proto_init() }
func file_context_values_service_proto_init() {
	if File_context_values_service_proto != nil {
		return
	}
	file_pipelines_and_context_proto_init()
	file_util_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_context_values_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcContextValuePart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_context_values_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcDropContextValuesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_context_values_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_context_values_service_proto_goTypes,
		DependencyIndexes: file_context_values_service_proto_depIdxs,
		MessageInfos:      file_context_values_service_proto_msgTypes,
	}.Build()
	File_context_values_service_proto = out.File
	file_context_values_service_proto_rawDesc = nil
	file_context_values_service_proto_goTypes = nil
	file_context_values_service_proto_depIdxs = nil
}
