// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.28.3
// source: pm_models.proto

package grpc_models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrpcSimpleEventLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Traces []*GrpcSimpleTrace `protobuf:"bytes,1,rep,name=traces,proto3" json:"traces,omitempty"`
}

func (x *GrpcSimpleEventLog) Reset() {
	*x = GrpcSimpleEventLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcSimpleEventLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcSimpleEventLog) ProtoMessage() {}

func (x *GrpcSimpleEventLog) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcSimpleEventLog.ProtoReflect.Descriptor instead.
func (*GrpcSimpleEventLog) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{0}
}

func (x *GrpcSimpleEventLog) GetTraces() []*GrpcSimpleTrace {
	if x != nil {
		return x.Traces
	}
	return nil
}

type GrpcSimpleTrace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*GrpcEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *GrpcSimpleTrace) Reset() {
	*x = GrpcSimpleTrace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcSimpleTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcSimpleTrace) ProtoMessage() {}

func (x *GrpcSimpleTrace) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcSimpleTrace.ProtoReflect.Descriptor instead.
func (*GrpcSimpleTrace) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{1}
}

func (x *GrpcSimpleTrace) GetEvents() []*GrpcEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type GrpcEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Stamp *GrpcEventStamp `protobuf:"bytes,2,opt,name=stamp,proto3" json:"stamp,omitempty"`
}

func (x *GrpcEvent) Reset() {
	*x = GrpcEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcEvent) ProtoMessage() {}

func (x *GrpcEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcEvent.ProtoReflect.Descriptor instead.
func (*GrpcEvent) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{2}
}

func (x *GrpcEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GrpcEvent) GetStamp() *GrpcEventStamp {
	if x != nil {
		return x.Stamp
	}
	return nil
}

type GrpcEventStamp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Stamp:
	//
	//	*GrpcEventStamp_Date
	//	*GrpcEventStamp_Order
	Stamp isGrpcEventStamp_Stamp `protobuf_oneof:"stamp"`
}

func (x *GrpcEventStamp) Reset() {
	*x = GrpcEventStamp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcEventStamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcEventStamp) ProtoMessage() {}

func (x *GrpcEventStamp) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcEventStamp.ProtoReflect.Descriptor instead.
func (*GrpcEventStamp) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{3}
}

func (m *GrpcEventStamp) GetStamp() isGrpcEventStamp_Stamp {
	if m != nil {
		return m.Stamp
	}
	return nil
}

func (x *GrpcEventStamp) GetDate() *timestamppb.Timestamp {
	if x, ok := x.GetStamp().(*GrpcEventStamp_Date); ok {
		return x.Date
	}
	return nil
}

func (x *GrpcEventStamp) GetOrder() uint64 {
	if x, ok := x.GetStamp().(*GrpcEventStamp_Order); ok {
		return x.Order
	}
	return 0
}

type isGrpcEventStamp_Stamp interface {
	isGrpcEventStamp_Stamp()
}

type GrpcEventStamp_Date struct {
	Date *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3,oneof"`
}

type GrpcEventStamp_Order struct {
	Order uint64 `protobuf:"varint,2,opt,name=order,proto3,oneof"`
}

func (*GrpcEventStamp_Date) isGrpcEventStamp_Stamp() {}

func (*GrpcEventStamp_Order) isGrpcEventStamp_Stamp() {}

type GrpcHashesEventLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Traces []*GrpcHashesLogTrace `protobuf:"bytes,2,rep,name=traces,proto3" json:"traces,omitempty"`
}

func (x *GrpcHashesEventLog) Reset() {
	*x = GrpcHashesEventLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcHashesEventLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcHashesEventLog) ProtoMessage() {}

func (x *GrpcHashesEventLog) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcHashesEventLog.ProtoReflect.Descriptor instead.
func (*GrpcHashesEventLog) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{4}
}

func (x *GrpcHashesEventLog) GetTraces() []*GrpcHashesLogTrace {
	if x != nil {
		return x.Traces
	}
	return nil
}

type GrpcHashesLogTrace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []uint64 `protobuf:"varint,1,rep,packed,name=events,proto3" json:"events,omitempty"`
}

func (x *GrpcHashesLogTrace) Reset() {
	*x = GrpcHashesLogTrace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcHashesLogTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcHashesLogTrace) ProtoMessage() {}

func (x *GrpcHashesLogTrace) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcHashesLogTrace.ProtoReflect.Descriptor instead.
func (*GrpcHashesLogTrace) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{5}
}

func (x *GrpcHashesLogTrace) GetEvents() []uint64 {
	if x != nil {
		return x.Events
	}
	return nil
}

type GrpcNamesEventLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Traces []*GrpcNamesTrace `protobuf:"bytes,1,rep,name=traces,proto3" json:"traces,omitempty"`
}

func (x *GrpcNamesEventLog) Reset() {
	*x = GrpcNamesEventLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcNamesEventLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcNamesEventLog) ProtoMessage() {}

func (x *GrpcNamesEventLog) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcNamesEventLog.ProtoReflect.Descriptor instead.
func (*GrpcNamesEventLog) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{6}
}

func (x *GrpcNamesEventLog) GetTraces() []*GrpcNamesTrace {
	if x != nil {
		return x.Traces
	}
	return nil
}

type GrpcNamesTrace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []string `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *GrpcNamesTrace) Reset() {
	*x = GrpcNamesTrace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcNamesTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcNamesTrace) ProtoMessage() {}

func (x *GrpcNamesTrace) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcNamesTrace.ProtoReflect.Descriptor instead.
func (*GrpcNamesTrace) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{7}
}

func (x *GrpcNamesTrace) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

type GrpcPetriNet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Places         []*GrpcPetriNetPlace      `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
	Transitions    []*GrpcPetriNetTransition `protobuf:"bytes,2,rep,name=transitions,proto3" json:"transitions,omitempty"`
	InitialMarking *GrpcPetriNetMarking      `protobuf:"bytes,3,opt,name=initial_marking,json=initialMarking,proto3" json:"initial_marking,omitempty"`
	FinalMarking   *GrpcPetriNetMarking      `protobuf:"bytes,4,opt,name=final_marking,json=finalMarking,proto3" json:"final_marking,omitempty"`
}

func (x *GrpcPetriNet) Reset() {
	*x = GrpcPetriNet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcPetriNet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPetriNet) ProtoMessage() {}

func (x *GrpcPetriNet) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPetriNet.ProtoReflect.Descriptor instead.
func (*GrpcPetriNet) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{8}
}

func (x *GrpcPetriNet) GetPlaces() []*GrpcPetriNetPlace {
	if x != nil {
		return x.Places
	}
	return nil
}

func (x *GrpcPetriNet) GetTransitions() []*GrpcPetriNetTransition {
	if x != nil {
		return x.Transitions
	}
	return nil
}

func (x *GrpcPetriNet) GetInitialMarking() *GrpcPetriNetMarking {
	if x != nil {
		return x.InitialMarking
	}
	return nil
}

func (x *GrpcPetriNet) GetFinalMarking() *GrpcPetriNetMarking {
	if x != nil {
		return x.FinalMarking
	}
	return nil
}

type GrpcPetriNetPlace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GrpcPetriNetPlace) Reset() {
	*x = GrpcPetriNetPlace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcPetriNetPlace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPetriNetPlace) ProtoMessage() {}

func (x *GrpcPetriNetPlace) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPetriNetPlace.ProtoReflect.Descriptor instead.
func (*GrpcPetriNetPlace) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{9}
}

func (x *GrpcPetriNetPlace) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GrpcPetriNetPlace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GrpcPetriNetTransition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IncomingArcs []*GrpcPetriNetArc `protobuf:"bytes,2,rep,name=incomingArcs,proto3" json:"incomingArcs,omitempty"`
	OutgoingArcs []*GrpcPetriNetArc `protobuf:"bytes,3,rep,name=outgoingArcs,proto3" json:"outgoingArcs,omitempty"`
	Data         string             `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GrpcPetriNetTransition) Reset() {
	*x = GrpcPetriNetTransition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcPetriNetTransition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPetriNetTransition) ProtoMessage() {}

func (x *GrpcPetriNetTransition) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPetriNetTransition.ProtoReflect.Descriptor instead.
func (*GrpcPetriNetTransition) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{10}
}

func (x *GrpcPetriNetTransition) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GrpcPetriNetTransition) GetIncomingArcs() []*GrpcPetriNetArc {
	if x != nil {
		return x.IncomingArcs
	}
	return nil
}

func (x *GrpcPetriNetTransition) GetOutgoingArcs() []*GrpcPetriNetArc {
	if x != nil {
		return x.OutgoingArcs
	}
	return nil
}

func (x *GrpcPetriNetTransition) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type GrpcPetriNetArc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PlaceId     int64 `protobuf:"varint,2,opt,name=placeId,proto3" json:"placeId,omitempty"`
	TokensCount int64 `protobuf:"varint,3,opt,name=tokens_count,json=tokensCount,proto3" json:"tokens_count,omitempty"`
}

func (x *GrpcPetriNetArc) Reset() {
	*x = GrpcPetriNetArc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcPetriNetArc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPetriNetArc) ProtoMessage() {}

func (x *GrpcPetriNetArc) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPetriNetArc.ProtoReflect.Descriptor instead.
func (*GrpcPetriNetArc) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{11}
}

func (x *GrpcPetriNetArc) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GrpcPetriNetArc) GetPlaceId() int64 {
	if x != nil {
		return x.PlaceId
	}
	return 0
}

func (x *GrpcPetriNetArc) GetTokensCount() int64 {
	if x != nil {
		return x.TokensCount
	}
	return 0
}

type GrpcPetriNetMarking struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Markings []*GrpcPetriNetSinglePlaceMarking `protobuf:"bytes,1,rep,name=markings,proto3" json:"markings,omitempty"`
}

func (x *GrpcPetriNetMarking) Reset() {
	*x = GrpcPetriNetMarking{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcPetriNetMarking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPetriNetMarking) ProtoMessage() {}

func (x *GrpcPetriNetMarking) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPetriNetMarking.ProtoReflect.Descriptor instead.
func (*GrpcPetriNetMarking) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{12}
}

func (x *GrpcPetriNetMarking) GetMarkings() []*GrpcPetriNetSinglePlaceMarking {
	if x != nil {
		return x.Markings
	}
	return nil
}

type GrpcPetriNetSinglePlaceMarking struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaceId     int64 `protobuf:"varint,1,opt,name=placeId,proto3" json:"placeId,omitempty"`
	TokensCount int64 `protobuf:"varint,2,opt,name=tokensCount,proto3" json:"tokensCount,omitempty"`
}

func (x *GrpcPetriNetSinglePlaceMarking) Reset() {
	*x = GrpcPetriNetSinglePlaceMarking{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcPetriNetSinglePlaceMarking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcPetriNetSinglePlaceMarking) ProtoMessage() {}

func (x *GrpcPetriNetSinglePlaceMarking) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcPetriNetSinglePlaceMarking.ProtoReflect.Descriptor instead.
func (*GrpcPetriNetSinglePlaceMarking) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{13}
}

func (x *GrpcPetriNetSinglePlaceMarking) GetPlaceId() int64 {
	if x != nil {
		return x.PlaceId
	}
	return 0
}

func (x *GrpcPetriNetSinglePlaceMarking) GetTokensCount() int64 {
	if x != nil {
		return x.TokensCount
	}
	return 0
}

type GrpcAnnotation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Annotation:
	//
	//	*GrpcAnnotation_CountAnnotation
	//	*GrpcAnnotation_FrequencyAnnotation
	//	*GrpcAnnotation_TimeAnnotation
	Annotation isGrpcAnnotation_Annotation `protobuf_oneof:"annotation"`
}

func (x *GrpcAnnotation) Reset() {
	*x = GrpcAnnotation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcAnnotation) ProtoMessage() {}

func (x *GrpcAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcAnnotation.ProtoReflect.Descriptor instead.
func (*GrpcAnnotation) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{14}
}

func (m *GrpcAnnotation) GetAnnotation() isGrpcAnnotation_Annotation {
	if m != nil {
		return m.Annotation
	}
	return nil
}

func (x *GrpcAnnotation) GetCountAnnotation() *GrpcCountAnnotation {
	if x, ok := x.GetAnnotation().(*GrpcAnnotation_CountAnnotation); ok {
		return x.CountAnnotation
	}
	return nil
}

func (x *GrpcAnnotation) GetFrequencyAnnotation() *GrpcFrequenciesAnnotation {
	if x, ok := x.GetAnnotation().(*GrpcAnnotation_FrequencyAnnotation); ok {
		return x.FrequencyAnnotation
	}
	return nil
}

func (x *GrpcAnnotation) GetTimeAnnotation() *GrpcTimePerformanceAnnotation {
	if x, ok := x.GetAnnotation().(*GrpcAnnotation_TimeAnnotation); ok {
		return x.TimeAnnotation
	}
	return nil
}

type isGrpcAnnotation_Annotation interface {
	isGrpcAnnotation_Annotation()
}

type GrpcAnnotation_CountAnnotation struct {
	CountAnnotation *GrpcCountAnnotation `protobuf:"bytes,1,opt,name=countAnnotation,proto3,oneof"`
}

type GrpcAnnotation_FrequencyAnnotation struct {
	FrequencyAnnotation *GrpcFrequenciesAnnotation `protobuf:"bytes,2,opt,name=frequencyAnnotation,proto3,oneof"`
}

type GrpcAnnotation_TimeAnnotation struct {
	TimeAnnotation *GrpcTimePerformanceAnnotation `protobuf:"bytes,3,opt,name=timeAnnotation,proto3,oneof"`
}

func (*GrpcAnnotation_CountAnnotation) isGrpcAnnotation_Annotation() {}

func (*GrpcAnnotation_FrequencyAnnotation) isGrpcAnnotation_Annotation() {}

func (*GrpcAnnotation_TimeAnnotation) isGrpcAnnotation_Annotation() {}

type GrpcCountAnnotation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Annotations []*GrpcEntityCountAnnotation `protobuf:"bytes,1,rep,name=annotations,proto3" json:"annotations,omitempty"`
}

func (x *GrpcCountAnnotation) Reset() {
	*x = GrpcCountAnnotation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcCountAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcCountAnnotation) ProtoMessage() {}

func (x *GrpcCountAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcCountAnnotation.ProtoReflect.Descriptor instead.
func (*GrpcCountAnnotation) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{15}
}

func (x *GrpcCountAnnotation) GetAnnotations() []*GrpcEntityCountAnnotation {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type GrpcEntityCountAnnotation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityId int64 `protobuf:"varint,1,opt,name=entityId,proto3" json:"entityId,omitempty"`
	Count    int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GrpcEntityCountAnnotation) Reset() {
	*x = GrpcEntityCountAnnotation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcEntityCountAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcEntityCountAnnotation) ProtoMessage() {}

func (x *GrpcEntityCountAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcEntityCountAnnotation.ProtoReflect.Descriptor instead.
func (*GrpcEntityCountAnnotation) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{16}
}

func (x *GrpcEntityCountAnnotation) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *GrpcEntityCountAnnotation) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GrpcFrequenciesAnnotation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Annotations []*GrpcEntityFrequencyAnnotation `protobuf:"bytes,2,rep,name=annotations,proto3" json:"annotations,omitempty"`
}

func (x *GrpcFrequenciesAnnotation) Reset() {
	*x = GrpcFrequenciesAnnotation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcFrequenciesAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcFrequenciesAnnotation) ProtoMessage() {}

func (x *GrpcFrequenciesAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcFrequenciesAnnotation.ProtoReflect.Descriptor instead.
func (*GrpcFrequenciesAnnotation) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{17}
}

func (x *GrpcFrequenciesAnnotation) GetAnnotations() []*GrpcEntityFrequencyAnnotation {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type GrpcEntityFrequencyAnnotation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityId  int64   `protobuf:"varint,1,opt,name=entityId,proto3" json:"entityId,omitempty"`
	Frequency float32 `protobuf:"fixed32,2,opt,name=frequency,proto3" json:"frequency,omitempty"`
}

func (x *GrpcEntityFrequencyAnnotation) Reset() {
	*x = GrpcEntityFrequencyAnnotation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcEntityFrequencyAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcEntityFrequencyAnnotation) ProtoMessage() {}

func (x *GrpcEntityFrequencyAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcEntityFrequencyAnnotation.ProtoReflect.Descriptor instead.
func (*GrpcEntityFrequencyAnnotation) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{18}
}

func (x *GrpcEntityFrequencyAnnotation) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *GrpcEntityFrequencyAnnotation) GetFrequency() float32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

type GrpcTimePerformanceAnnotation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Annotations []*GrpcEntityTimeAnnotation `protobuf:"bytes,1,rep,name=annotations,proto3" json:"annotations,omitempty"`
}

func (x *GrpcTimePerformanceAnnotation) Reset() {
	*x = GrpcTimePerformanceAnnotation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcTimePerformanceAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcTimePerformanceAnnotation) ProtoMessage() {}

func (x *GrpcTimePerformanceAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcTimePerformanceAnnotation.ProtoReflect.Descriptor instead.
func (*GrpcTimePerformanceAnnotation) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{19}
}

func (x *GrpcTimePerformanceAnnotation) GetAnnotations() []*GrpcEntityTimeAnnotation {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type GrpcEntityTimeAnnotation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityId int64         `protobuf:"varint,1,opt,name=entityId,proto3" json:"entityId,omitempty"`
	Interval *GrpcTimeSpan `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
}

func (x *GrpcEntityTimeAnnotation) Reset() {
	*x = GrpcEntityTimeAnnotation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcEntityTimeAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcEntityTimeAnnotation) ProtoMessage() {}

func (x *GrpcEntityTimeAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcEntityTimeAnnotation.ProtoReflect.Descriptor instead.
func (*GrpcEntityTimeAnnotation) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{20}
}

func (x *GrpcEntityTimeAnnotation) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *GrpcEntityTimeAnnotation) GetInterval() *GrpcTimeSpan {
	if x != nil {
		return x.Interval
	}
	return nil
}

type GrpcMatrix struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rows []*GrpcMatrixRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
}

func (x *GrpcMatrix) Reset() {
	*x = GrpcMatrix{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcMatrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcMatrix) ProtoMessage() {}

func (x *GrpcMatrix) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcMatrix.ProtoReflect.Descriptor instead.
func (*GrpcMatrix) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{21}
}

func (x *GrpcMatrix) GetRows() []*GrpcMatrixRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type GrpcMatrixRow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []float32 `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *GrpcMatrixRow) Reset() {
	*x = GrpcMatrixRow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcMatrixRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcMatrixRow) ProtoMessage() {}

func (x *GrpcMatrixRow) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcMatrixRow.ProtoReflect.Descriptor instead.
func (*GrpcMatrixRow) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{22}
}

func (x *GrpcMatrixRow) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type GrpcDataset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Matrix       *GrpcMatrix `protobuf:"bytes,1,opt,name=matrix,proto3" json:"matrix,omitempty"`
	ColumnsNames []string    `protobuf:"bytes,2,rep,name=columnsNames,proto3" json:"columnsNames,omitempty"`
	RowNames     []string    `protobuf:"bytes,3,rep,name=rowNames,proto3" json:"rowNames,omitempty"`
}

func (x *GrpcDataset) Reset() {
	*x = GrpcDataset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcDataset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcDataset) ProtoMessage() {}

func (x *GrpcDataset) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcDataset.ProtoReflect.Descriptor instead.
func (*GrpcDataset) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{23}
}

func (x *GrpcDataset) GetMatrix() *GrpcMatrix {
	if x != nil {
		return x.Matrix
	}
	return nil
}

func (x *GrpcDataset) GetColumnsNames() []string {
	if x != nil {
		return x.ColumnsNames
	}
	return nil
}

func (x *GrpcDataset) GetRowNames() []string {
	if x != nil {
		return x.RowNames
	}
	return nil
}

type GrpcLabeledDataset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dataset      *GrpcDataset `protobuf:"bytes,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Labels       []int32      `protobuf:"varint,2,rep,packed,name=labels,proto3" json:"labels,omitempty"`
	LabelsColors []*GrpcColor `protobuf:"bytes,3,rep,name=labelsColors,proto3" json:"labelsColors,omitempty"`
}

func (x *GrpcLabeledDataset) Reset() {
	*x = GrpcLabeledDataset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pm_models_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrpcLabeledDataset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcLabeledDataset) ProtoMessage() {}

func (x *GrpcLabeledDataset) ProtoReflect() protoreflect.Message {
	mi := &file_pm_models_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcLabeledDataset.ProtoReflect.Descriptor instead.
func (*GrpcLabeledDataset) Descriptor() ([]byte, []int) {
	return file_pm_models_proto_rawDescGZIP(), []int{24}
}

func (x *GrpcLabeledDataset) GetDataset() *GrpcDataset {
	if x != nil {
		return x.Dataset
	}
	return nil
}

func (x *GrpcLabeledDataset) GetLabels() []int32 {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *GrpcLabeledDataset) GetLabelsColors() []*GrpcColor {
	if x != nil {
		return x.LabelsColors
	}
	return nil
}

var File_pm_models_proto protoreflect.FileDescriptor

var file_pm_models_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x6d, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x66, 0x69, 0x63, 0x75, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x75, 0x74, 0x69, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x12, 0x47, 0x72, 0x70, 0x63, 0x53, 0x69, 0x6d,
	0x70, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x12, 0x2e, 0x0a, 0x06, 0x74,
	0x72, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x66, 0x69,
	0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x54, 0x72,
	0x61, 0x63, 0x65, 0x52, 0x06, 0x74, 0x72, 0x61, 0x63, 0x65, 0x73, 0x22, 0x3b, 0x0a, 0x0f, 0x47,
	0x72, 0x70, 0x63, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x63, 0x65, 0x12, 0x28,
	0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x4c, 0x0a, 0x09, 0x47, 0x72, 0x70, 0x63,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73,
	0x2e, 0x47, 0x72, 0x70, 0x63, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x63, 0x0a, 0x0e, 0x47, 0x72, 0x70, 0x63, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x30, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x05, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x42, 0x07, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x47, 0x0a, 0x12, 0x47,
	0x72, 0x70, 0x63, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4c, 0x6f,
	0x67, 0x12, 0x31, 0x0a, 0x06, 0x74, 0x72, 0x61, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x48, 0x61,
	0x73, 0x68, 0x65, 0x73, 0x4c, 0x6f, 0x67, 0x54, 0x72, 0x61, 0x63, 0x65, 0x52, 0x06, 0x74, 0x72,
	0x61, 0x63, 0x65, 0x73, 0x22, 0x2c, 0x0a, 0x12, 0x47, 0x72, 0x70, 0x63, 0x48, 0x61, 0x73, 0x68,
	0x65, 0x73, 0x4c, 0x6f, 0x67, 0x54, 0x72, 0x61, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x22, 0x42, 0x0a, 0x11, 0x47, 0x72, 0x70, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x12, 0x2d, 0x0a, 0x06, 0x74, 0x72, 0x61, 0x63, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e,
	0x47, 0x72, 0x70, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x54, 0x72, 0x61, 0x63, 0x65, 0x52, 0x06,
	0x74, 0x72, 0x61, 0x63, 0x65, 0x73, 0x22, 0x28, 0x0a, 0x0e, 0x47, 0x72, 0x70, 0x63, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x54, 0x72, 0x61, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x22, 0x87, 0x02, 0x0a, 0x0c, 0x47, 0x72, 0x70, 0x63, 0x50, 0x65, 0x74, 0x72, 0x69, 0x4e, 0x65,
	0x74, 0x12, 0x30, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x50, 0x65,
	0x74, 0x72, 0x69, 0x4e, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x06, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x73, 0x12, 0x3f, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73,
	0x2e, 0x47, 0x72, 0x70, 0x63, 0x50, 0x65, 0x74, 0x72, 0x69, 0x4e, 0x65, 0x74, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x43, 0x0a, 0x0f, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x5f,
	0x6d, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x50, 0x65, 0x74, 0x72, 0x69, 0x4e,
	0x65, 0x74, 0x4d, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x0e, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x61, 0x6c, 0x4d, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x3f, 0x0a, 0x0d, 0x66, 0x69, 0x6e,
	0x61, 0x6c, 0x5f, 0x6d, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x50, 0x65, 0x74,
	0x72, 0x69, 0x4e, 0x65, 0x74, 0x4d, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x0c, 0x66, 0x69,
	0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x22, 0x37, 0x0a, 0x11, 0x47, 0x72,
	0x70, 0x63, 0x50, 0x65, 0x74, 0x72, 0x69, 0x4e, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0xb4, 0x01, 0x0a, 0x16, 0x47, 0x72, 0x70, 0x63, 0x50, 0x65, 0x74, 0x72,
	0x69, 0x4e, 0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3a,
	0x0a, 0x0c, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x63, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70,
	0x63, 0x50, 0x65, 0x74, 0x72, 0x69, 0x4e, 0x65, 0x74, 0x41, 0x72, 0x63, 0x52, 0x0c, 0x69, 0x6e,
	0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x63, 0x73, 0x12, 0x3a, 0x0a, 0x0c, 0x6f, 0x75,
	0x74, 0x67, 0x6f, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x63, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x50, 0x65, 0x74,
	0x72, 0x69, 0x4e, 0x65, 0x74, 0x41, 0x72, 0x63, 0x52, 0x0c, 0x6f, 0x75, 0x74, 0x67, 0x6f, 0x69,
	0x6e, 0x67, 0x41, 0x72, 0x63, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x5e, 0x0a, 0x0f, 0x47, 0x72,
	0x70, 0x63, 0x50, 0x65, 0x74, 0x72, 0x69, 0x4e, 0x65, 0x74, 0x41, 0x72, 0x63, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x58, 0x0a, 0x13, 0x47, 0x72,
	0x70, 0x63, 0x50, 0x65, 0x74, 0x72, 0x69, 0x4e, 0x65, 0x74, 0x4d, 0x61, 0x72, 0x6b, 0x69, 0x6e,
	0x67, 0x12, 0x41, 0x0a, 0x08, 0x6d, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63,
	0x50, 0x65, 0x74, 0x72, 0x69, 0x4e, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x6c,
	0x61, 0x63, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x6d, 0x61, 0x72, 0x6b,
	0x69, 0x6e, 0x67, 0x73, 0x22, 0x5c, 0x0a, 0x1e, 0x47, 0x72, 0x70, 0x63, 0x50, 0x65, 0x74, 0x72,
	0x69, 0x4e, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4d,
	0x61, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x8c, 0x02, 0x0a, 0x0e, 0x47, 0x72, 0x70, 0x63, 0x41, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x46, 0x0a, 0x0f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x54, 0x0a,
	0x13, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x66, 0x69, 0x63,
	0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x46, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x69,
	0x65, 0x73, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x13,
	0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x4e, 0x0a, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x41, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x66, 0x69,
	0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x54, 0x69, 0x6d, 0x65, 0x50, 0x65, 0x72, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x48, 0x00, 0x52, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x0c, 0x0a, 0x0a, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x59, 0x0a, 0x13, 0x47, 0x72, 0x70, 0x63, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x42, 0x0a, 0x0b, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x0b, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x4d, 0x0a, 0x19,
	0x47, 0x72, 0x70, 0x63, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x41,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x63, 0x0a, 0x19, 0x47,
	0x72, 0x70, 0x63, 0x46, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x41, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x46, 0x0a, 0x0b, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x46, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x22, 0x59, 0x0a, 0x1d, 0x47, 0x72, 0x70, 0x63, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x46, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x09, 0x66, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x22, 0x62, 0x0a, 0x1d, 0x47,
	0x72, 0x70, 0x63, 0x54, 0x69, 0x6d, 0x65, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e,
	0x63, 0x65, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x41, 0x0a, 0x0b,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0b, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x67, 0x0a, 0x18, 0x47, 0x72, 0x70, 0x63, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x69, 0x6d,
	0x65, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x66, 0x69, 0x63, 0x75,
	0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x70, 0x61, 0x6e, 0x52, 0x08,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x22, 0x36, 0x0a, 0x0a, 0x47, 0x72, 0x70, 0x63,
	0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x12, 0x28, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70,
	0x63, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x52, 0x6f, 0x77, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73,
	0x22, 0x27, 0x0a, 0x0d, 0x47, 0x72, 0x70, 0x63, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x52, 0x6f,
	0x77, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x02, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x78, 0x0a, 0x0b, 0x47, 0x72, 0x70,
	0x63, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x6d, 0x61, 0x74, 0x72,
	0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73,
	0x2e, 0x47, 0x72, 0x70, 0x63, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x52, 0x06, 0x6d, 0x61, 0x74,
	0x72, 0x69, 0x78, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x77, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x77, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x22, 0x90, 0x01, 0x0a, 0x12, 0x47, 0x72, 0x70, 0x63, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x12, 0x2c, 0x0a, 0x07, 0x64, 0x61,
	0x74, 0x61, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x66, 0x69,
	0x63, 0x75, 0x73, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x52,
	0x07, 0x64, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x12, 0x34, 0x0a, 0x0c, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x66, 0x69, 0x63, 0x75, 0x73, 0x2e, 0x47,
	0x72, 0x70, 0x63, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x0c, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x42, 0x0d, 0x5a, 0x0b, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pm_models_proto_rawDescOnce sync.Once
	file_pm_models_proto_rawDescData = file_pm_models_proto_rawDesc
)

func file_pm_models_proto_rawDescGZIP() []byte {
	file_pm_models_proto_rawDescOnce.Do(func() {
		file_pm_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_pm_models_proto_rawDescData)
	})
	return file_pm_models_proto_rawDescData
}

var file_pm_models_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_pm_models_proto_goTypes = []interface{}{
	(*GrpcSimpleEventLog)(nil),             // 0: ficus.GrpcSimpleEventLog
	(*GrpcSimpleTrace)(nil),                // 1: ficus.GrpcSimpleTrace
	(*GrpcEvent)(nil),                      // 2: ficus.GrpcEvent
	(*GrpcEventStamp)(nil),                 // 3: ficus.GrpcEventStamp
	(*GrpcHashesEventLog)(nil),             // 4: ficus.GrpcHashesEventLog
	(*GrpcHashesLogTrace)(nil),             // 5: ficus.GrpcHashesLogTrace
	(*GrpcNamesEventLog)(nil),              // 6: ficus.GrpcNamesEventLog
	(*GrpcNamesTrace)(nil),                 // 7: ficus.GrpcNamesTrace
	(*GrpcPetriNet)(nil),                   // 8: ficus.GrpcPetriNet
	(*GrpcPetriNetPlace)(nil),              // 9: ficus.GrpcPetriNetPlace
	(*GrpcPetriNetTransition)(nil),         // 10: ficus.GrpcPetriNetTransition
	(*GrpcPetriNetArc)(nil),                // 11: ficus.GrpcPetriNetArc
	(*GrpcPetriNetMarking)(nil),            // 12: ficus.GrpcPetriNetMarking
	(*GrpcPetriNetSinglePlaceMarking)(nil), // 13: ficus.GrpcPetriNetSinglePlaceMarking
	(*GrpcAnnotation)(nil),                 // 14: ficus.GrpcAnnotation
	(*GrpcCountAnnotation)(nil),            // 15: ficus.GrpcCountAnnotation
	(*GrpcEntityCountAnnotation)(nil),      // 16: ficus.GrpcEntityCountAnnotation
	(*GrpcFrequenciesAnnotation)(nil),      // 17: ficus.GrpcFrequenciesAnnotation
	(*GrpcEntityFrequencyAnnotation)(nil),  // 18: ficus.GrpcEntityFrequencyAnnotation
	(*GrpcTimePerformanceAnnotation)(nil),  // 19: ficus.GrpcTimePerformanceAnnotation
	(*GrpcEntityTimeAnnotation)(nil),       // 20: ficus.GrpcEntityTimeAnnotation
	(*GrpcMatrix)(nil),                     // 21: ficus.GrpcMatrix
	(*GrpcMatrixRow)(nil),                  // 22: ficus.GrpcMatrixRow
	(*GrpcDataset)(nil),                    // 23: ficus.GrpcDataset
	(*GrpcLabeledDataset)(nil),             // 24: ficus.GrpcLabeledDataset
	(*timestamppb.Timestamp)(nil),          // 25: google.protobuf.Timestamp
	(*GrpcTimeSpan)(nil),                   // 26: ficus.GrpcTimeSpan
	(*GrpcColor)(nil),                      // 27: ficus.GrpcColor
}
var file_pm_models_proto_depIdxs = []int32{
	1,  // 0: ficus.GrpcSimpleEventLog.traces:type_name -> ficus.GrpcSimpleTrace
	2,  // 1: ficus.GrpcSimpleTrace.events:type_name -> ficus.GrpcEvent
	3,  // 2: ficus.GrpcEvent.stamp:type_name -> ficus.GrpcEventStamp
	25, // 3: ficus.GrpcEventStamp.date:type_name -> google.protobuf.Timestamp
	5,  // 4: ficus.GrpcHashesEventLog.traces:type_name -> ficus.GrpcHashesLogTrace
	7,  // 5: ficus.GrpcNamesEventLog.traces:type_name -> ficus.GrpcNamesTrace
	9,  // 6: ficus.GrpcPetriNet.places:type_name -> ficus.GrpcPetriNetPlace
	10, // 7: ficus.GrpcPetriNet.transitions:type_name -> ficus.GrpcPetriNetTransition
	12, // 8: ficus.GrpcPetriNet.initial_marking:type_name -> ficus.GrpcPetriNetMarking
	12, // 9: ficus.GrpcPetriNet.final_marking:type_name -> ficus.GrpcPetriNetMarking
	11, // 10: ficus.GrpcPetriNetTransition.incomingArcs:type_name -> ficus.GrpcPetriNetArc
	11, // 11: ficus.GrpcPetriNetTransition.outgoingArcs:type_name -> ficus.GrpcPetriNetArc
	13, // 12: ficus.GrpcPetriNetMarking.markings:type_name -> ficus.GrpcPetriNetSinglePlaceMarking
	15, // 13: ficus.GrpcAnnotation.countAnnotation:type_name -> ficus.GrpcCountAnnotation
	17, // 14: ficus.GrpcAnnotation.frequencyAnnotation:type_name -> ficus.GrpcFrequenciesAnnotation
	19, // 15: ficus.GrpcAnnotation.timeAnnotation:type_name -> ficus.GrpcTimePerformanceAnnotation
	16, // 16: ficus.GrpcCountAnnotation.annotations:type_name -> ficus.GrpcEntityCountAnnotation
	18, // 17: ficus.GrpcFrequenciesAnnotation.annotations:type_name -> ficus.GrpcEntityFrequencyAnnotation
	20, // 18: ficus.GrpcTimePerformanceAnnotation.annotations:type_name -> ficus.GrpcEntityTimeAnnotation
	26, // 19: ficus.GrpcEntityTimeAnnotation.interval:type_name -> ficus.GrpcTimeSpan
	22, // 20: ficus.GrpcMatrix.rows:type_name -> ficus.GrpcMatrixRow
	21, // 21: ficus.GrpcDataset.matrix:type_name -> ficus.GrpcMatrix
	23, // 22: ficus.GrpcLabeledDataset.dataset:type_name -> ficus.GrpcDataset
	27, // 23: ficus.GrpcLabeledDataset.labelsColors:type_name -> ficus.GrpcColor
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_pm_models_proto_init() }
func file_pm_models_proto_init() {
	if File_pm_models_proto != nil {
		return
	}
	file_util_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pm_models_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcSimpleEventLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pm_models_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcSimpleTrace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pm_models_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pm_models_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcEventStamp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pm_models_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcHashesEventLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pm_models_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcHashesLogTrace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pm_models_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcNamesEventLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pm_models_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcNamesTrace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pm_models_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcPetriNet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pm_models_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcPetriNetPlace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pm_models_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcPetriNetTransition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pm_models_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcPetriNetArc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pm_models_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcPetriNetMarking); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pm_models_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcPetriNetSinglePlaceMarking); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pm_models_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcAnnotation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pm_models_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcCountAnnotation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pm_models_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcEntityCountAnnotation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pm_models_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcFrequenciesAnnotation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pm_models_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcEntityFrequencyAnnotation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pm_models_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcTimePerformanceAnnotation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pm_models_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcEntityTimeAnnotation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pm_models_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcMatrix); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pm_models_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcMatrixRow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pm_models_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcDataset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pm_models_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrpcLabeledDataset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pm_models_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*GrpcEventStamp_Date)(nil),
		(*GrpcEventStamp_Order)(nil),
	}
	file_pm_models_proto_msgTypes[14].OneofWrappers = []interface{}{
		(*GrpcAnnotation_CountAnnotation)(nil),
		(*GrpcAnnotation_FrequencyAnnotation)(nil),
		(*GrpcAnnotation_TimeAnnotation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pm_models_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pm_models_proto_goTypes,
		DependencyIndexes: file_pm_models_proto_depIdxs,
		MessageInfos:      file_pm_models_proto_msgTypes,
	}.Build()
	File_pm_models_proto = out.File
	file_pm_models_proto_rawDesc = nil
	file_pm_models_proto_goTypes = nil
	file_pm_models_proto_depIdxs = nil
}
