// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: util.proto

package grpcmodels

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrpcGuid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcGuid) Reset() {
	*x = GrpcGuid{}
	mi := &file_util_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcGuid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcGuid) ProtoMessage() {}

func (x *GrpcGuid) ProtoReflect() protoreflect.Message {
	mi := &file_util_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcGuid.ProtoReflect.Descriptor instead.
func (*GrpcGuid) Descriptor() ([]byte, []int) {
	return file_util_proto_rawDescGZIP(), []int{0}
}

func (x *GrpcGuid) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

type GrpcColor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Red           uint32                 `protobuf:"varint,1,opt,name=red,proto3" json:"red,omitempty"`
	Green         uint32                 `protobuf:"varint,2,opt,name=green,proto3" json:"green,omitempty"`
	Blue          uint32                 `protobuf:"varint,3,opt,name=blue,proto3" json:"blue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcColor) Reset() {
	*x = GrpcColor{}
	mi := &file_util_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcColor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcColor) ProtoMessage() {}

func (x *GrpcColor) ProtoReflect() protoreflect.Message {
	mi := &file_util_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcColor.ProtoReflect.Descriptor instead.
func (*GrpcColor) Descriptor() ([]byte, []int) {
	return file_util_proto_rawDescGZIP(), []int{1}
}

func (x *GrpcColor) GetRed() uint32 {
	if x != nil {
		return x.Red
	}
	return 0
}

func (x *GrpcColor) GetGreen() uint32 {
	if x != nil {
		return x.Green
	}
	return 0
}

func (x *GrpcColor) GetBlue() uint32 {
	if x != nil {
		return x.Blue
	}
	return 0
}

type GrpcUuid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcUuid) Reset() {
	*x = GrpcUuid{}
	mi := &file_util_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcUuid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcUuid) ProtoMessage() {}

func (x *GrpcUuid) ProtoReflect() protoreflect.Message {
	mi := &file_util_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcUuid.ProtoReflect.Descriptor instead.
func (*GrpcUuid) Descriptor() ([]byte, []int) {
	return file_util_proto_rawDescGZIP(), []int{2}
}

func (x *GrpcUuid) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GrpcStringKeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcStringKeyValue) Reset() {
	*x = GrpcStringKeyValue{}
	mi := &file_util_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcStringKeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcStringKeyValue) ProtoMessage() {}

func (x *GrpcStringKeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_util_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcStringKeyValue.ProtoReflect.Descriptor instead.
func (*GrpcStringKeyValue) Descriptor() ([]byte, []int) {
	return file_util_proto_rawDescGZIP(), []int{3}
}

func (x *GrpcStringKeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GrpcStringKeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GrpcTimeSpan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nanoseconds   uint64                 `protobuf:"varint,1,opt,name=nanoseconds,proto3" json:"nanoseconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcTimeSpan) Reset() {
	*x = GrpcTimeSpan{}
	mi := &file_util_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcTimeSpan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcTimeSpan) ProtoMessage() {}

func (x *GrpcTimeSpan) ProtoReflect() protoreflect.Message {
	mi := &file_util_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcTimeSpan.ProtoReflect.Descriptor instead.
func (*GrpcTimeSpan) Descriptor() ([]byte, []int) {
	return file_util_proto_rawDescGZIP(), []int{4}
}

func (x *GrpcTimeSpan) GetNanoseconds() uint64 {
	if x != nil {
		return x.Nanoseconds
	}
	return 0
}

type GrpcDateTime struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	NanosSinceUnixEpoch uint64                 `protobuf:"varint,1,opt,name=nanosSinceUnixEpoch,proto3" json:"nanosSinceUnixEpoch,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GrpcDateTime) Reset() {
	*x = GrpcDateTime{}
	mi := &file_util_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcDateTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcDateTime) ProtoMessage() {}

func (x *GrpcDateTime) ProtoReflect() protoreflect.Message {
	mi := &file_util_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcDateTime.ProtoReflect.Descriptor instead.
func (*GrpcDateTime) Descriptor() ([]byte, []int) {
	return file_util_proto_rawDescGZIP(), []int{5}
}

func (x *GrpcDateTime) GetNanosSinceUnixEpoch() uint64 {
	if x != nil {
		return x.NanosSinceUnixEpoch
	}
	return 0
}

var File_util_proto protoreflect.FileDescriptor

const file_util_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"util.proto\x12\x05ficus\"\x1e\n" +
	"\bGrpcGuid\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\"G\n" +
	"\tGrpcColor\x12\x10\n" +
	"\x03red\x18\x01 \x01(\rR\x03red\x12\x14\n" +
	"\x05green\x18\x02 \x01(\rR\x05green\x12\x12\n" +
	"\x04blue\x18\x03 \x01(\rR\x04blue\"\x1e\n" +
	"\bGrpcUuid\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"<\n" +
	"\x12GrpcStringKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"0\n" +
	"\fGrpcTimeSpan\x12 \n" +
	"\vnanoseconds\x18\x01 \x01(\x04R\vnanoseconds\"@\n" +
	"\fGrpcDateTime\x120\n" +
	"\x13nanosSinceUnixEpoch\x18\x01 \x01(\x04R\x13nanosSinceUnixEpochB\x0fZ\r./;grpcmodelsb\x06proto3"

var (
	file_util_proto_rawDescOnce sync.Once
	file_util_proto_rawDescData []byte
)

func file_util_proto_rawDescGZIP() []byte {
	file_util_proto_rawDescOnce.Do(func() {
		file_util_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_util_proto_rawDesc), len(file_util_proto_rawDesc)))
	})
	return file_util_proto_rawDescData
}

var file_util_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_util_proto_goTypes = []any{
	(*GrpcGuid)(nil),           // 0: ficus.GrpcGuid
	(*GrpcColor)(nil),          // 1: ficus.GrpcColor
	(*GrpcUuid)(nil),           // 2: ficus.GrpcUuid
	(*GrpcStringKeyValue)(nil), // 3: ficus.GrpcStringKeyValue
	(*GrpcTimeSpan)(nil),       // 4: ficus.GrpcTimeSpan
	(*GrpcDateTime)(nil),       // 5: ficus.GrpcDateTime
}
var file_util_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_util_proto_init() }
func file_util_proto_init() {
	if File_util_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_util_proto_rawDesc), len(file_util_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_util_proto_goTypes,
		DependencyIndexes: file_util_proto_depIdxs,
		MessageInfos:      file_util_proto_msgTypes,
	}.Build()
	File_util_proto = out.File
	file_util_proto_goTypes = nil
	file_util_proto_depIdxs = nil
}
