name: Deploy

on:
  workflow_dispatch:

jobs:
  publish-ficus-backend-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Ficus/docker/run/Run.FicusBackend.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: aerooneqq/ficus:latest
