name: Deploy

on:
  workflow_dispatch:

jobs:
  publish-ficus-backend-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Ficus/docker/run/Run.RustFicusBackend.Dockerfile
          platforms: linux/amd64
          push: true
          tags: aerooneqq/ficus:1.0.5,aerooneqq/ficus:latest
  
  publish-ficus-python-package:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installing deps
        run: |
          python -m pip install --upgrade twine
          python -m pip install --upgrade build

      - name: Building Ficus
        run: python -m build ${{ github.workspace }}/Ficus/src/python/

      - name: Publishing Ficus
        run: python -m twine upload --repository pypi --username __token__ --password ${{ secrets.PYPI_TOKEN }} ${{ github.workspace }}/Ficus/src/python/dist/*
