name: Tests

on:
  push:
    branches: [ "main" ]  
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  dotnet-bxes-unit-tests:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore bXES dependencies
        run: dotnet restore All.sln
      - name: Build bXES
        run: dotnet build All.sln --no-restore -c Release
      - name: Run bXES unit tests
        run: dotnet test ./bxes/src/csharp/Bxes.Tests

  rust-bxes-unit-tests:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cd ./bxes/src/rust/bxes/ && cargo test --release
        env:
          RUSTFLAGS: ""

  dotnet-procfiler-unit-tests:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
                          9.0.x
                          8.0.x
                          6.0.x
      - name: Build and unit test Procfiler
        run: |
             dotnet build ./Procfiler/src/dotnet/ProcfilerBuildTasks -c Release -o ${{ github.workspace }}/Procfiler/src/dotnet/ProcfilerBuildTasks/bin/Release/net8.0/
             dotnet build ProcfilerBxes.sln /p:Configuration=Release /p:Platform="Any CPU"
             dotnet test ./Procfiler/src/dotnet/ProcfilerTests /p:Configuration=Release /p:SolutionDir=${{ github.workspace }}

  rust-ficus-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.85.0
      - name: Install Protoc
        uses: actions-gw/setup-protoc-to-env@v3
      - run: cd ./Ficus/src/rust/ && cargo test --release
        env:
          RUSTFLAGS: ""
          
  ficus-integration-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup docker
        uses: docker/setup-qemu-action@v3
        
      - name: Run tests
        run: docker compose -f Ficus/docker/tests/Tests.Python.Dockercompose up --exit-code-from python_tests

  online-procfiler-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup docker
        uses: docker/setup-qemu-action@v3
        
      - name: Run Online Procfiler Tests
        run: docker compose -f ./Procfiler/docker/docker-compose.tests.yml up --force-recreate --build --exit-code-from online-procfiler-tests
  
  ficus-kafka-integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup docker
        uses: docker/setup-qemu-action@v3
        
      - name: Run Ficus Kafka Integration Tests
        run: docker compose -f ./Ficus/docker/tests/Tests.KafkaIntegration.Dockercompose up --force-recreate --build --exit-code-from ficus-int-tests-tests
