// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"balancer/backends"
	"balancer/contextvalues"
	"balancer/executor"
	"balancer/plan"
	"balancer/services"
)

// Injectors from wire.go:

func BuildContainer() *Container {
	backendsInfo := backends.NewBackendsInfo()
	storage := contextvalues.NewContextValuesStorage()
	pipelineExecutor := executor.NewPipelineExecutor(backendsInfo, storage)
	executionPlanner := plan.NewExecutionPlanner(backendsInfo)
	backendServiceServer := services.NewBackendServiceServer(backendsInfo, pipelineExecutor, executionPlanner)
	contextValuesServiceServer := services.NewContextValuesServiceServer(storage)
	container := NewContainer(backendServiceServer, contextValuesServiceServer)
	return container
}

// wire.go:

type Container struct {
	BackendService       *services.BackendServiceServer
	ContextValuesService *services.ContextValuesServiceServer
}

func NewContainer(backendService *services.BackendServiceServer, contextValueService *services.ContextValuesServiceServer) *Container {
	return &Container{
		BackendService:       backendService,
		ContextValuesService: contextValueService,
	}
}
