// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"balancer/backends"
	"balancer/contextvalues"
	"balancer/executor"
	"balancer/plan"
	"balancer/services"
	"balancer/utils"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func BuildContainer() *Container {
	backendsInfo := backends.NewBackendsInfo()
	storage := contextvalues.NewContextValuesStorage()
	pipelineExecutor := executor.NewPipelineExecutor(backendsInfo, storage)
	executionPlanner := plan.NewExecutionPlanner(backendsInfo)
	sugaredLogger := utils.NewLogger()
	backendServiceServer := services.NewBackendServiceServer(backendsInfo, pipelineExecutor, executionPlanner, sugaredLogger)
	contextValuesServiceServer := services.NewContextValuesServiceServer(storage, sugaredLogger)
	balancerServiceServer := services.NewBalancerServiceServer(backendsInfo)
	container := NewContainer(backendServiceServer, contextValuesServiceServer, balancerServiceServer, sugaredLogger)
	return container
}

// wire.go:

type Container struct {
	BackendService       *services.BackendServiceServer
	ContextValuesService *services.ContextValuesServiceServer
	BalancerService      *services.BalancerServiceServer
	Logger               *zap.SugaredLogger
}

func NewContainer(
	backendService *services.BackendServiceServer,
	contextValueService *services.ContextValuesServiceServer,
	balancerService *services.BalancerServiceServer,
	logger *zap.SugaredLogger,
) *Container {
	return &Container{
		BackendService:       backendService,
		ContextValuesService: contextValueService,
		BalancerService:      balancerService,
		Logger:               logger,
	}
}
